// SPDX-License-Identifier: Apache-2.0

//! The `expressions` table — FRBR expression identity.
//!
//! An *expression* is one manifestation-class of a work: a particular
//! translation, edition, or printing. Its `content_sha256` is the
//! content signature that defines the expression's text. Like `works`,
//! this is a deliberately thin v1 table — by decision D3 the FRBR layer
//! is built but left empty during the pilot. `work_id` links to `works`
//! as a bare soft reference, never a foreign key.

use bookrack_dbkit::{ColumnSpec, IndexSpec, TableSpec};
use rusqlite::{OptionalExtension, Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `expressions` table's schema. Its
/// DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "expressions",
    comment: Some("One manifestation-class of a work: a translation, an edition."),
    columns: &[
        ColumnSpec::int("expression_id").pk_autoinc(),
        ColumnSpec::int("work_id").comment("soft reference to works"),
        ColumnSpec::text("content_sha256")
            .comment("content signature defining this expression's text"),
        ColumnSpec::text("kind").comment("translation / edition / printing"),
        ColumnSpec::text("label"),
        ColumnSpec::text("notes"),
        ColumnSpec::text("curated_at"),
        ColumnSpec::text("curated_by"),
    ],
    composite_pk: None,
    uniques: &[],
    table_checks: &[],
    indexes: &[IndexSpec::on("idx_expr_content", &["content_sha256"])
        .partial("content_sha256 IS NOT NULL")],
};

/// Insert one expression and return its surrogate id. `curated_at` is
/// generated by SQLite so the whole crate shares one timestamp source.
const INSERT_SQL: &str = "INSERT INTO expressions \
     (work_id, content_sha256, kind, label, notes, curated_at, curated_by) \
     VALUES (:work_id, :content_sha256, :kind, :label, :notes, \
             strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :curated_by) \
     RETURNING expression_id";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM expressions {tail}", SPEC.select_list())
}

/// One `expressions` row — a curated FRBR expression.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Expression {
    /// Surrogate key, assigned by the database.
    pub expression_id: i64,
    /// The work this expression realizes — a soft reference to `works`.
    pub work_id: Option<i64>,
    /// The content signature defining this expression's text.
    pub content_sha256: Option<String>,
    /// The kind of expression (`translation` / `edition` / `printing`).
    pub kind: Option<String>,
    /// A short human-readable label.
    pub label: Option<String>,
    /// Free-form curator notes.
    pub notes: Option<String>,
    /// When the expression was curated, ISO-8601 UTC.
    pub curated_at: Option<String>,
    /// Who curated the expression.
    pub curated_by: Option<String>,
}

impl Expression {
    /// Build an [`Expression`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<Expression> {
        Ok(Expression {
            expression_id: row.get("expression_id")?,
            work_id: row.get("work_id")?,
            content_sha256: row.get("content_sha256")?,
            kind: row.get("kind")?,
            label: row.get("label")?,
            notes: row.get("notes")?,
            curated_at: row.get("curated_at")?,
            curated_by: row.get("curated_by")?,
        })
    }
}

/// An expression about to be written. The surrogate `expression_id` and
/// the `curated_at` timestamp are assigned by the database. Every other
/// field is optional, so the fields are public; [`NewExpression::new`]
/// starts from an empty expression.
#[derive(Debug, Clone)]
pub struct NewExpression {
    /// The work this expression realizes.
    pub work_id: Option<i64>,
    /// The content signature defining this expression's text.
    pub content_sha256: Option<String>,
    /// The kind of expression.
    pub kind: Option<String>,
    /// A short human-readable label.
    pub label: Option<String>,
    /// Free-form curator notes.
    pub notes: Option<String>,
    /// Who curated the expression.
    pub curated_by: Option<String>,
}

impl NewExpression {
    /// An empty expression, with every field cleared.
    pub fn new() -> NewExpression {
        NewExpression {
            work_id: None,
            content_sha256: None,
            kind: None,
            label: None,
            notes: None,
            curated_by: None,
        }
    }
}

impl Default for NewExpression {
    fn default() -> NewExpression {
        NewExpression::new()
    }
}

impl Catalog {
    /// Insert one expression, returning its assigned `expression_id`.
    pub fn add_expression(&self, new: &NewExpression) -> Result<i64> {
        let id = self.conn.query_row(
            INSERT_SQL,
            named_params! {
                ":work_id": new.work_id,
                ":content_sha256": new.content_sha256,
                ":kind": new.kind,
                ":label": new.label,
                ":notes": new.notes,
                ":curated_by": new.curated_by,
            },
            |row| row.get(0),
        )?;
        Ok(id)
    }

    /// Fetch one expression by its id, or `None` if there is none.
    pub fn expression(&self, expression_id: i64) -> Result<Option<Expression>> {
        let expression = self
            .conn
            .query_row(
                &select_sql("WHERE expression_id = :expression_id"),
                named_params! { ":expression_id": expression_id },
                Expression::from_row,
            )
            .optional()?;
        Ok(expression)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_expression_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        let mut new = NewExpression::new();
        new.work_id = Some(7);
        new.content_sha256 = Some("sha-content".into());
        new.kind = Some("translation".into());
        new.label = Some("English, 1998".into());
        new.notes = Some("the revised translation".into());
        new.curated_by = Some("human".into());
        let id = catalog.add_expression(&new).expect("add");
        assert!(id > 0);

        let read = catalog.expression(id).expect("read").expect("present");
        assert_eq!(read.expression_id, id);
        assert_eq!(read.work_id, Some(7));
        assert_eq!(read.content_sha256.as_deref(), Some("sha-content"));
        assert_eq!(read.kind.as_deref(), Some("translation"));
        assert_eq!(read.label.as_deref(), Some("English, 1998"));
        assert_eq!(read.notes.as_deref(), Some("the revised translation"));
        assert!(read.curated_at.is_some_and(|at| !at.is_empty()));
        assert_eq!(read.curated_by.as_deref(), Some("human"));
    }

    #[test]
    fn a_missing_expression_reads_as_none() {
        let catalog = Catalog::open_in_memory().expect("open");
        assert!(catalog.expression(404).expect("read").is_none());
    }
}
