// SPDX-License-Identifier: Apache-2.0

//! The `mcp_tool_calls` table — the MCP / CLI tool-call log.
//!
//! One append-only row per tool invocation, whether it came in over the
//! MCP server or the CLI: what was called, how it ended, how long it
//! took, and the JSON payloads around it. It is an observability table —
//! diagnostic, trimmable, never a source of truth.

use bookrack_dbkit::{ColumnSpec, IndexSpec, TableSpec};
use rusqlite::{Connection, Row, named_params};

use crate::retrieval_calls::NewRetrievalCall;
use crate::{Catalog, Result, retrieval_call_hits, retrieval_calls};

/// The single source of truth for the `mcp_tool_calls` table's schema.
/// Its DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "mcp_tool_calls",
    comment: Some("Observability: the MCP / CLI tool-call log."),
    columns: &[
        ColumnSpec::int("call_id").pk_autoinc(),
        ColumnSpec::text("ts").not_null(),
        ColumnSpec::text("source").not_null().comment("mcp / cli"),
        ColumnSpec::text("tool").not_null(),
        ColumnSpec::text("status").not_null().comment("ok / error"),
        ColumnSpec::real("duration_ms"),
        ColumnSpec::text("session_id"),
        ColumnSpec::text("error_type"),
        ColumnSpec::text("error_msg"),
        ColumnSpec::text("args").comment("JSON"),
        ColumnSpec::text("timings_ms").comment("JSON"),
        ColumnSpec::text("extras").comment("JSON"),
    ],
    composite_pk: None,
    uniques: &[],
    table_checks: &[],
    indexes: &[IndexSpec::on("idx_mcp_tool_ts", &["tool", "ts"])],
};

/// Insert one tool-call row and return its surrogate id. `ts` is
/// generated by SQLite so the whole crate shares one timestamp source.
const INSERT_SQL: &str = "INSERT INTO mcp_tool_calls \
     (ts, source, tool, status, duration_ms, session_id, error_type, \
      error_msg, args, timings_ms, extras) \
     VALUES (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :source, :tool, :status, \
             :duration_ms, :session_id, :error_type, :error_msg, :args, \
             :timings_ms, :extras) \
     RETURNING call_id";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM mcp_tool_calls {tail}", SPEC.select_list())
}

/// One `mcp_tool_calls` row — a single recorded tool invocation.
#[derive(Debug, Clone, PartialEq)]
pub struct McpToolCall {
    /// Surrogate key, assigned by the database.
    pub call_id: i64,
    /// When the call was logged, ISO-8601 UTC.
    pub ts: String,
    /// Where the call came from (`mcp` / `cli`).
    pub source: String,
    /// The invoked tool.
    pub tool: String,
    /// How the call ended (`ok` / `error`).
    pub status: String,
    /// How long the call took, in milliseconds.
    pub duration_ms: Option<f64>,
    /// The session the call belongs to.
    pub session_id: Option<String>,
    /// The error class, when the call failed.
    pub error_type: Option<String>,
    /// The error message, when the call failed.
    pub error_msg: Option<String>,
    /// The call arguments, as JSON.
    pub args: Option<String>,
    /// A JSON breakdown of internal timings.
    pub timings_ms: Option<String>,
    /// Any further JSON detail.
    pub extras: Option<String>,
}

impl McpToolCall {
    /// Build an [`McpToolCall`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<McpToolCall> {
        Ok(McpToolCall {
            call_id: row.get("call_id")?,
            ts: row.get("ts")?,
            source: row.get("source")?,
            tool: row.get("tool")?,
            status: row.get("status")?,
            duration_ms: row.get("duration_ms")?,
            session_id: row.get("session_id")?,
            error_type: row.get("error_type")?,
            error_msg: row.get("error_msg")?,
            args: row.get("args")?,
            timings_ms: row.get("timings_ms")?,
            extras: row.get("extras")?,
        })
    }
}

/// A tool-call row about to be written. The surrogate `call_id` and the
/// `ts` timestamp are assigned by the database. The row is a flat record
/// written as a unit, so its fields are public rather than builder
/// methods; [`NewMcpToolCall::new`] sets the mandatory ones.
#[derive(Debug, Clone)]
pub struct NewMcpToolCall {
    /// Where the call came from.
    pub source: String,
    /// The invoked tool.
    pub tool: String,
    /// How the call ended.
    pub status: String,
    /// How long the call took, in milliseconds.
    pub duration_ms: Option<f64>,
    /// The session the call belongs to.
    pub session_id: Option<String>,
    /// The error class, when the call failed.
    pub error_type: Option<String>,
    /// The error message, when the call failed.
    pub error_msg: Option<String>,
    /// The call arguments, as JSON.
    pub args: Option<String>,
    /// A JSON breakdown of internal timings.
    pub timings_ms: Option<String>,
    /// Any further JSON detail.
    pub extras: Option<String>,
}

impl NewMcpToolCall {
    /// A tool call from `source` of `tool` ending in `status`, with
    /// every optional field cleared.
    pub fn new(
        source: impl Into<String>,
        tool: impl Into<String>,
        status: impl Into<String>,
    ) -> NewMcpToolCall {
        NewMcpToolCall {
            source: source.into(),
            tool: tool.into(),
            status: status.into(),
            duration_ms: None,
            session_id: None,
            error_type: None,
            error_msg: None,
            args: None,
            timings_ms: None,
            extras: None,
        }
    }
}

/// Insert one tool-call row on `conn`, which may be inside a
/// transaction, returning the assigned `call_id`.
fn insert_tool_call(conn: &Connection, new: &NewMcpToolCall) -> rusqlite::Result<i64> {
    conn.query_row(
        INSERT_SQL,
        named_params! {
            ":source": new.source,
            ":tool": new.tool,
            ":status": new.status,
            ":duration_ms": new.duration_ms,
            ":session_id": new.session_id,
            ":error_type": new.error_type,
            ":error_msg": new.error_msg,
            ":args": new.args,
            ":timings_ms": new.timings_ms,
            ":extras": new.extras,
        },
        |row| row.get(0),
    )
}

impl Catalog {
    /// Append one row to the tool-call log, returning its `call_id`.
    pub fn record_tool_call(&self, new: &NewMcpToolCall) -> Result<i64> {
        Ok(insert_tool_call(&self.conn, new)?)
    }

    /// Append one row to the tool-call log and, when `retrieval` is
    /// set, its retrieval sidecar: the `retrieval_calls` row and one
    /// `retrieval_call_hits` row per hit. All inserts share one
    /// transaction, so the log row and its sidecar land together or
    /// not at all. Returns the shared `call_id`.
    pub fn record_tool_call_with_retrieval(
        &self,
        new: &NewMcpToolCall,
        retrieval: Option<&NewRetrievalCall>,
    ) -> Result<i64> {
        let tx = self.conn.unchecked_transaction()?;
        let call_id = insert_tool_call(&tx, new)?;
        if let Some(retrieval) = retrieval {
            retrieval_calls::insert_retrieval_call(&tx, call_id, retrieval)?;
            retrieval_call_hits::insert_retrieval_call_hits(&tx, call_id, &retrieval.hits)?;
        }
        tx.commit()?;
        Ok(call_id)
    }

    /// Every logged call of `tool`, oldest first.
    pub fn tool_calls_for_tool(&self, tool: &str) -> Result<Vec<McpToolCall>> {
        let mut stmt = self
            .conn
            .prepare(&select_sql("WHERE tool = :tool ORDER BY ts, call_id"))?;
        let rows = stmt
            .query_map(named_params! { ":tool": tool }, McpToolCall::from_row)?
            .collect::<rusqlite::Result<Vec<McpToolCall>>>()?;
        Ok(rows)
    }

    /// Tool calls with `ts >= since_ts`, newest first, capped at `limit`
    /// rows. The forensic time window the diagnose command consumes.
    pub fn recent_tool_calls(&self, since_ts: &str, limit: u32) -> Result<Vec<McpToolCall>> {
        let mut stmt = self.conn.prepare(&select_sql(
            "WHERE ts >= :since_ts ORDER BY ts DESC, call_id DESC LIMIT :limit",
        ))?;
        let rows = stmt
            .query_map(
                named_params! { ":since_ts": since_ts, ":limit": limit },
                McpToolCall::from_row,
            )?
            .collect::<rusqlite::Result<Vec<McpToolCall>>>()?;
        Ok(rows)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A `NewMcpToolCall` with every optional field set, so a dropped
    /// column or unbound parameter fails an assertion.
    fn fully_populated() -> NewMcpToolCall {
        let mut call = NewMcpToolCall::new("mcp", "search_library", "error");
        // 12.5 is exactly representable, so the round-trip is exact.
        call.duration_ms = Some(12.5);
        call.session_id = Some("sess-1".into());
        call.error_type = Some("timeout".into());
        call.error_msg = Some("the request timed out".into());
        call.args = Some(r#"{"query":"x"}"#.into());
        call.timings_ms = Some(r#"{"embed":4.0}"#.into());
        call.extras = Some(r#"{"retries":2}"#.into());
        call
    }

    #[test]
    fn a_tool_call_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        let id = catalog
            .record_tool_call(&fully_populated())
            .expect("record");
        assert!(id > 0);

        let all = catalog.tool_calls_for_tool("search_library").expect("read");
        assert_eq!(all.len(), 1);
        let row = &all[0];
        assert_eq!(row.call_id, id);
        assert!(!row.ts.is_empty());
        assert_eq!(row.source, "mcp");
        assert_eq!(row.tool, "search_library");
        assert_eq!(row.status, "error");
        assert_eq!(row.duration_ms, Some(12.5));
        assert_eq!(row.session_id.as_deref(), Some("sess-1"));
        assert_eq!(row.error_type.as_deref(), Some("timeout"));
        assert_eq!(row.error_msg.as_deref(), Some("the request timed out"));
        assert_eq!(row.args.as_deref(), Some(r#"{"query":"x"}"#));
        assert_eq!(row.timings_ms.as_deref(), Some(r#"{"embed":4.0}"#));
        assert_eq!(row.extras.as_deref(), Some(r#"{"retries":2}"#));
    }

    #[test]
    fn calls_of_one_tool_come_back_in_insertion_order() {
        let catalog = Catalog::open_in_memory().expect("open");
        for status in ["ok", "ok", "error"] {
            catalog
                .record_tool_call(&NewMcpToolCall::new("cli", "get_book_context", status))
                .expect("record");
        }
        // A call of a different tool must not leak into the result.
        catalog
            .record_tool_call(&NewMcpToolCall::new("cli", "list_books", "ok"))
            .expect("record");

        let statuses: Vec<String> = catalog
            .tool_calls_for_tool("get_book_context")
            .expect("read")
            .into_iter()
            .map(|row| row.status)
            .collect();
        assert_eq!(statuses, ["ok", "ok", "error"]);
    }

    #[test]
    fn an_unlogged_tool_reads_empty() {
        let catalog = Catalog::open_in_memory().expect("open");
        assert!(
            catalog
                .tool_calls_for_tool("never_called")
                .expect("read")
                .is_empty()
        );
    }

    /// Insert a row, then back-date its `ts` so the cutoff query has
    /// something deterministic to compare against. The default `ts` is
    /// `now`, which would make a `since_ts` filter useless in a unit test.
    fn record_at(catalog: &Catalog, ts: &str, tool: &str, status: &str) -> i64 {
        let id = catalog
            .record_tool_call(&NewMcpToolCall::new("cli", tool, status))
            .expect("record");
        catalog
            .conn
            .execute(
                "UPDATE mcp_tool_calls SET ts = ?1 WHERE call_id = ?2",
                rusqlite::params![ts, id],
            )
            .expect("backdate ts");
        id
    }

    #[test]
    fn recent_tool_calls_returns_rows_since_cutoff_newest_first() {
        let catalog = Catalog::open_in_memory().expect("open");
        record_at(&catalog, "2026-06-01T00:00:00Z", "tool_a", "ok");
        record_at(&catalog, "2026-06-02T00:00:00Z", "tool_b", "ok");
        record_at(&catalog, "2026-06-03T00:00:00Z", "tool_c", "error");

        let rows = catalog
            .recent_tool_calls("2026-06-02T00:00:00Z", 10)
            .expect("read");
        let tools: Vec<&str> = rows.iter().map(|r| r.tool.as_str()).collect();
        assert_eq!(tools, ["tool_c", "tool_b"]);
    }

    #[test]
    fn recent_tool_calls_respects_the_limit() {
        let catalog = Catalog::open_in_memory().expect("open");
        for day in 1..=5 {
            record_at(
                &catalog,
                &format!("2026-06-0{day}T00:00:00Z"),
                "tool_x",
                "ok",
            );
        }
        let rows = catalog
            .recent_tool_calls("2026-06-01T00:00:00Z", 2)
            .expect("read");
        assert_eq!(rows.len(), 2);
    }

    fn retrieval_payload() -> NewRetrievalCall {
        NewRetrievalCall {
            fingerprint: "deadbeefcafef00d".to_string(),
            top_k: 5,
            query_text: Some("what is a monad".to_string()),
            hits: vec![
                ("p-alpha".to_string(), 0.12),
                ("p-beta".to_string(), 0.34),
                ("p-gamma".to_string(), 0.56),
            ],
        }
    }

    fn table_counts(catalog: &Catalog) -> (i64, i64, i64) {
        let count = |table: &str| -> i64 {
            catalog
                .conn
                .query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |row| {
                    row.get(0)
                })
                .expect("count")
        };
        (
            count("mcp_tool_calls"),
            count("retrieval_calls"),
            count("retrieval_call_hits"),
        )
    }

    #[test]
    fn record_tool_call_with_retrieval_writes_three_tables() {
        let catalog = Catalog::open_in_memory().expect("open");
        let call_id = catalog
            .record_tool_call_with_retrieval(
                &NewMcpToolCall::new("mcp", "search", "ok"),
                Some(&retrieval_payload()),
            )
            .expect("record");
        assert_eq!(table_counts(&catalog), (1, 1, 3));

        let logged = catalog.tool_calls_for_tool("search").expect("read log");
        assert_eq!(logged[0].call_id, call_id);
        let call = catalog
            .retrieval_call(call_id)
            .expect("read")
            .expect("present");
        assert_eq!(call.corpus_fingerprint, "deadbeefcafef00d");
        assert_eq!(call.top_k_requested, 5);
        assert_eq!(call.n_hits, 3);
        assert_eq!(call.query_text.as_deref(), Some("what is a monad"));
        let hits = catalog.retrieval_hits(call_id).expect("read hits");
        assert_eq!(hits.len(), 3);
        assert_eq!(hits[2].passage_id, "p-gamma");
        assert_eq!(hits[2].distance, f64::from(0.56f32));
    }

    #[test]
    fn record_tool_call_with_no_retrieval_leaves_the_sidecar_empty() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .record_tool_call_with_retrieval(
                &NewMcpToolCall::new("cli", "papers_dryrun", "ok"),
                None,
            )
            .expect("record");
        assert_eq!(table_counts(&catalog), (1, 0, 0));
    }

    #[test]
    fn record_tool_call_with_retrieval_rolls_back_on_hit_insert_failure() {
        let catalog = Catalog::open_in_memory().expect("open");
        // Fault injection: abort the second hit insert, after the log
        // row, the sidecar row, and the first hit have already landed
        // inside the transaction.
        catalog
            .conn
            .execute_batch(
                "CREATE TEMP TRIGGER fail_second_hit \
                 BEFORE INSERT ON retrieval_call_hits WHEN NEW.ord = 1 \
                 BEGIN SELECT RAISE(ABORT, 'injected hit failure'); END;",
            )
            .expect("create fault trigger");

        let result = catalog.record_tool_call_with_retrieval(
            &NewMcpToolCall::new("mcp", "search", "ok"),
            Some(&retrieval_payload()),
        );
        assert!(result.is_err());
        // The whole transaction rolled back: no log row, no sidecar
        // row, no hit row survives the partial write.
        assert_eq!(table_counts(&catalog), (0, 0, 0));
    }
}
