// SPDX-License-Identifier: Apache-2.0

//! The `metadata_audit` table — the metadata-edit audit trail.
//!
//! One append-only row per user edit to curated metadata (and to the TOC
//! overlay), carrying the before and after values. It backs the edit
//! history and undo. A row outlives the node it describes: `node_id` is a
//! bare soft reference, never a foreign key, so deleting a book leaves
//! its audit trail intact.

use bookrack_dbkit::{ColumnSpec, IndexSpec, TableSpec, decode};
use rusqlite::{Row, named_params};

use crate::{ActorKind, Catalog, Result};

/// The single source of truth for the `metadata_audit` table's schema.
/// Its DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "metadata_audit",
    comment: Some("Audit trail of user metadata edits; supports history and undo."),
    columns: &[
        ColumnSpec::int("audit_id").pk_autoinc(),
        ColumnSpec::int("node_id").comment("soft reference; audit outlives the node"),
        ColumnSpec::text("table_name").not_null(),
        ColumnSpec::text("field").comment("NULL for a row-level insert/delete"),
        ColumnSpec::text("action").not_null(),
        ColumnSpec::text("old_value"),
        ColumnSpec::text("new_value"),
        ColumnSpec::text("changed_at").not_null(),
        ColumnSpec::text("actor_kind")
            .not_null()
            .check("actor_kind IN ('human', 'llm', 'import', 'pipeline', 'system')"),
        ColumnSpec::text("actor_detail"),
        ColumnSpec::text("reason"),
        ColumnSpec::text("session_id"),
    ],
    composite_pk: None,
    uniques: &[],
    table_checks: &[],
    indexes: &[
        IndexSpec::on("idx_audit_node", &["node_id", "changed_at"]),
        IndexSpec::on("idx_audit_session", &["session_id"]),
    ],
};

/// Insert one audit row and return its surrogate id. `changed_at` is
/// generated by SQLite so the whole crate shares one timestamp source.
const INSERT_SQL: &str = "INSERT INTO metadata_audit \
     (node_id, table_name, field, action, old_value, new_value, changed_at, \
      actor_kind, actor_detail, reason, session_id) \
     VALUES (:node_id, :table_name, :field, :action, :old_value, :new_value, \
             strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :actor_kind, :actor_detail, \
             :reason, :session_id) \
     RETURNING audit_id";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM metadata_audit {tail}", SPEC.select_list())
}

/// One `metadata_audit` row — a single recorded metadata edit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MetadataAudit {
    /// Surrogate key, assigned by the database.
    pub audit_id: i64,
    /// The edited node — a soft reference; `None` for a non-node edit.
    pub node_id: Option<i64>,
    /// The table the edit touched.
    pub table_name: String,
    /// The edited field; `None` for a row-level insert or delete.
    pub field: Option<String>,
    /// What happened (`insert` / `update` / `delete` / ...).
    pub action: String,
    /// The value before the edit, when there was one.
    pub old_value: Option<String>,
    /// The value after the edit, when there is one.
    pub new_value: Option<String>,
    /// When the edit was made, ISO-8601 UTC.
    pub changed_at: String,
    /// What kind of actor made the edit.
    pub actor_kind: ActorKind,
    /// The variable part of the actor's identity (model name, ...).
    pub actor_detail: Option<String>,
    /// Why the edit was made.
    pub reason: Option<String>,
    /// The session the edit belongs to.
    pub session_id: Option<String>,
}

impl MetadataAudit {
    /// Build a [`MetadataAudit`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<MetadataAudit> {
        Ok(MetadataAudit {
            audit_id: row.get("audit_id")?,
            node_id: row.get("node_id")?,
            table_name: row.get("table_name")?,
            field: row.get("field")?,
            action: row.get("action")?,
            old_value: row.get("old_value")?,
            new_value: row.get("new_value")?,
            changed_at: row.get("changed_at")?,
            actor_kind: decode(row, "actor_kind", ActorKind::from_db_str)?,
            actor_detail: row.get("actor_detail")?,
            reason: row.get("reason")?,
            session_id: row.get("session_id")?,
        })
    }
}

/// An audit row about to be written. The surrogate `audit_id` and the
/// `changed_at` timestamp are assigned by the database. The row is a flat
/// record written as a unit, so its fields are public rather than builder
/// methods; [`NewMetadataAudit::new`] sets the mandatory ones.
#[derive(Debug, Clone)]
pub struct NewMetadataAudit {
    /// The edited node, when the edit concerns one.
    pub node_id: Option<i64>,
    /// The table the edit touched.
    pub table_name: String,
    /// The edited field; leave `None` for a row-level insert or delete.
    pub field: Option<String>,
    /// What happened.
    pub action: String,
    /// The value before the edit.
    pub old_value: Option<String>,
    /// The value after the edit.
    pub new_value: Option<String>,
    /// What kind of actor made the edit.
    pub actor_kind: ActorKind,
    /// The variable part of the actor's identity.
    pub actor_detail: Option<String>,
    /// Why the edit was made.
    pub reason: Option<String>,
    /// The session the edit belongs to.
    pub session_id: Option<String>,
}

impl NewMetadataAudit {
    /// An audit row for `action` on `table_name` by `actor_kind`, with
    /// every optional field cleared.
    pub fn new(
        table_name: impl Into<String>,
        action: impl Into<String>,
        actor_kind: ActorKind,
    ) -> NewMetadataAudit {
        NewMetadataAudit {
            node_id: None,
            table_name: table_name.into(),
            field: None,
            action: action.into(),
            old_value: None,
            new_value: None,
            actor_kind,
            actor_detail: None,
            reason: None,
            session_id: None,
        }
    }
}

impl Catalog {
    /// Append one row to the metadata-edit audit trail, returning its
    /// assigned `audit_id`.
    pub fn record_metadata_audit(&self, new: &NewMetadataAudit) -> Result<i64> {
        let id = self.conn.query_row(
            INSERT_SQL,
            named_params! {
                ":node_id": new.node_id,
                ":table_name": new.table_name,
                ":field": new.field,
                ":action": new.action,
                ":old_value": new.old_value,
                ":new_value": new.new_value,
                ":actor_kind": new.actor_kind.as_str(),
                ":actor_detail": new.actor_detail,
                ":reason": new.reason,
                ":session_id": new.session_id,
            },
            |row| row.get(0),
        )?;
        Ok(id)
    }

    /// Every audit row for `node_id`, oldest first.
    pub fn metadata_audit_for_node(&self, node_id: i64) -> Result<Vec<MetadataAudit>> {
        let mut stmt = self.conn.prepare(&select_sql(
            "WHERE node_id = :node_id ORDER BY changed_at, audit_id",
        ))?;
        let rows = stmt
            .query_map(
                named_params! { ":node_id": node_id },
                MetadataAudit::from_row,
            )?
            .collect::<rusqlite::Result<Vec<MetadataAudit>>>()?;
        Ok(rows)
    }

    /// Metadata-audit rows with `changed_at >= since_ts`, newest first,
    /// capped at `limit` rows. The forensic time window the diagnose
    /// collector consumes.
    pub fn recent_metadata_audit(&self, since_ts: &str, limit: u32) -> Result<Vec<MetadataAudit>> {
        let mut stmt = self.conn.prepare(&select_sql(
            "WHERE changed_at >= :since_ts ORDER BY changed_at DESC, audit_id DESC LIMIT :limit",
        ))?;
        let rows = stmt
            .query_map(
                named_params! { ":since_ts": since_ts, ":limit": limit },
                MetadataAudit::from_row,
            )?
            .collect::<rusqlite::Result<Vec<MetadataAudit>>>()?;
        Ok(rows)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A `NewMetadataAudit` with every optional field set, so a dropped
    /// column or unbound parameter fails an assertion.
    fn fully_populated() -> NewMetadataAudit {
        let mut audit = NewMetadataAudit::new("node_overrides", "update", ActorKind::Human);
        audit.node_id = Some(100_000_001);
        audit.field = Some("title".into());
        audit.old_value = Some("Old Title".into());
        audit.new_value = Some("New Title".into());
        audit.actor_detail = Some("operator".into());
        audit.reason = Some("fixed a typo".into());
        audit.session_id = Some("sess-1".into());
        audit
    }

    #[test]
    fn a_metadata_audit_row_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        let id = catalog
            .record_metadata_audit(&fully_populated())
            .expect("record");
        assert!(id > 0);

        let all = catalog.metadata_audit_for_node(100_000_001).expect("read");
        assert_eq!(all.len(), 1);
        let row = &all[0];
        assert_eq!(row.audit_id, id);
        assert_eq!(row.node_id, Some(100_000_001));
        assert_eq!(row.table_name, "node_overrides");
        assert_eq!(row.field.as_deref(), Some("title"));
        assert_eq!(row.action, "update");
        assert_eq!(row.old_value.as_deref(), Some("Old Title"));
        assert_eq!(row.new_value.as_deref(), Some("New Title"));
        assert!(!row.changed_at.is_empty());
        assert_eq!(row.actor_kind, ActorKind::Human);
        assert_eq!(row.actor_detail.as_deref(), Some("operator"));
        assert_eq!(row.reason.as_deref(), Some("fixed a typo"));
        assert_eq!(row.session_id.as_deref(), Some("sess-1"));
    }

    #[test]
    fn audit_rows_for_a_node_come_back_in_insertion_order() {
        let catalog = Catalog::open_in_memory().expect("open");
        for action in ["insert", "update", "delete"] {
            let mut audit = NewMetadataAudit::new("node_overrides", action, ActorKind::Human);
            audit.node_id = Some(100_000_001);
            catalog.record_metadata_audit(&audit).expect("record");
        }
        let actions: Vec<String> = catalog
            .metadata_audit_for_node(100_000_001)
            .expect("read")
            .into_iter()
            .map(|row| row.action)
            .collect();
        assert_eq!(actions, ["insert", "update", "delete"]);
    }

    /// Insert a row, then back-date its `changed_at` so a cutoff filter
    /// has something deterministic to compare against. The default
    /// `changed_at` is `now`, which would defeat a `since_ts` filter in
    /// a unit test.
    fn record_at(catalog: &Catalog, ts: &str, action: &str) -> i64 {
        let mut audit = NewMetadataAudit::new("node_overrides", action, ActorKind::Human);
        audit.node_id = Some(100_000_001);
        let id = catalog.record_metadata_audit(&audit).expect("record");
        catalog
            .conn
            .execute(
                "UPDATE metadata_audit SET changed_at = ?1 WHERE audit_id = ?2",
                rusqlite::params![ts, id],
            )
            .expect("backdate changed_at");
        id
    }

    #[test]
    fn recent_metadata_audit_returns_rows_since_cutoff_newest_first() {
        let catalog = Catalog::open_in_memory().expect("open");
        record_at(&catalog, "2026-06-01T00:00:00Z", "insert");
        record_at(&catalog, "2026-06-02T00:00:00Z", "update");
        record_at(&catalog, "2026-06-03T00:00:00Z", "delete");

        let rows = catalog
            .recent_metadata_audit("2026-06-02T00:00:00Z", 10)
            .expect("read");
        let actions: Vec<&str> = rows.iter().map(|r| r.action.as_str()).collect();
        assert_eq!(actions, ["delete", "update"]);
    }

    #[test]
    fn a_node_with_no_audit_history_reads_empty() {
        let catalog = Catalog::open_in_memory().expect("open");
        assert!(
            catalog
                .metadata_audit_for_node(404)
                .expect("read")
                .is_empty()
        );
    }
}
