// SPDX-License-Identifier: Apache-2.0

//! The `node_reviews` table — per-node review status.
//!
//! One row per reviewed node, recording the outcome of a human review
//! pass. The row is keyed by node id and rewritten on each review.

use bookrack_dbkit::{ColumnSpec, TableSpec};
use rusqlite::{OptionalExtension, Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `node_reviews` table's schema. Its
/// DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "node_reviews",
    comment: Some("Per-node review status."),
    columns: &[
        ColumnSpec::int("node_id").primary_key(),
        ColumnSpec::text("reviewed_at").not_null(),
        ColumnSpec::text("reviewed_by").not_null(),
        ColumnSpec::text("status")
            .not_null()
            .comment("clean / needs_work / rejected"),
        ColumnSpec::text("notes"),
    ],
    composite_pk: None,
    uniques: &[],
    table_checks: &[],
    indexes: &[],
};

/// Insert or replace a node's review, keyed by `node_id`. `reviewed_at`
/// is generated by SQLite so the whole crate shares one timestamp source.
const UPSERT_SQL: &str = "INSERT INTO node_reviews \
     (node_id, reviewed_at, reviewed_by, status, notes) \
     VALUES (:node_id, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :reviewed_by, :status, :notes) \
     ON CONFLICT(node_id) DO UPDATE SET \
       reviewed_at = excluded.reviewed_at, \
       reviewed_by = excluded.reviewed_by, \
       status = excluded.status, \
       notes = excluded.notes";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM node_reviews {tail}", SPEC.select_list())
}

/// One `node_reviews` row — the outcome of one node's review.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeReview {
    /// The reviewed node.
    pub node_id: i64,
    /// When the review was made, ISO-8601 UTC.
    pub reviewed_at: String,
    /// Who made the review.
    pub reviewed_by: String,
    /// The review outcome (`clean` / `needs_work` / `rejected`).
    pub status: String,
    /// Free-form notes.
    pub notes: Option<String>,
}

impl NodeReview {
    /// Build a [`NodeReview`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<NodeReview> {
        Ok(NodeReview {
            node_id: row.get("node_id")?,
            reviewed_at: row.get("reviewed_at")?,
            reviewed_by: row.get("reviewed_by")?,
            status: row.get("status")?,
            notes: row.get("notes")?,
        })
    }
}

/// A review about to be written.
#[derive(Debug, Clone)]
pub struct NewReview {
    node_id: i64,
    reviewed_by: String,
    status: String,
    notes: Option<String>,
}

impl NewReview {
    /// A review of `node_id` with the given outcome, note-free until the
    /// builder says otherwise.
    pub fn new(
        node_id: i64,
        reviewed_by: impl Into<String>,
        status: impl Into<String>,
    ) -> NewReview {
        NewReview {
            node_id,
            reviewed_by: reviewed_by.into(),
            status: status.into(),
            notes: None,
        }
    }

    /// Attach free-form notes.
    pub fn notes(mut self, notes: impl Into<String>) -> NewReview {
        self.notes = Some(notes.into());
        self
    }
}

impl Catalog {
    /// Insert or replace a node's review.
    pub fn upsert_review(&self, new: &NewReview) -> Result<()> {
        self.conn.execute(
            UPSERT_SQL,
            named_params! {
                ":node_id": new.node_id,
                ":reviewed_by": new.reviewed_by,
                ":status": new.status,
                ":notes": new.notes,
            },
        )?;
        Ok(())
    }

    /// Fetch a node's review, or `None` if it has not been reviewed.
    pub fn review(&self, node_id: i64) -> Result<Option<NodeReview>> {
        let review = self
            .conn
            .query_row(
                &select_sql("WHERE node_id = :node_id"),
                named_params! { ":node_id": node_id },
                NodeReview::from_row,
            )
            .optional()?;
        Ok(review)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_review_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .upsert_review(
                &NewReview::new(100_000_001, "human", "needs_work").notes("check the TOC"),
            )
            .expect("write");

        let read = catalog.review(100_000_001).expect("read").expect("present");
        assert_eq!(read.node_id, 100_000_001);
        assert!(!read.reviewed_at.is_empty());
        assert_eq!(read.reviewed_by, "human");
        assert_eq!(read.status, "needs_work");
        assert_eq!(read.notes.as_deref(), Some("check the TOC"));
    }

    #[test]
    fn a_missing_review_reads_as_none() {
        let catalog = Catalog::open_in_memory().expect("open");
        assert!(catalog.review(404).expect("read").is_none());
    }

    #[test]
    fn upsert_overwrites_a_previous_review() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .upsert_review(&NewReview::new(100_000_001, "human", "needs_work"))
            .expect("first review");
        catalog
            .upsert_review(&NewReview::new(100_000_001, "human", "clean"))
            .expect("second review");
        let read = catalog.review(100_000_001).expect("read").expect("present");
        assert_eq!(read.status, "clean");
    }
}
