// SPDX-License-Identifier: Apache-2.0

//! The `node_role_takeovers` table — explicit role-takeover markers.
//!
//! One row per (node, role) the user has taken over. The marker
//! resolves an ambiguity: an empty list of *user* contributors for a
//! role could mean either "the user has not curated this role" or "the
//! user has deliberately cleared it". A takeover row says it is the
//! latter.

use bookrack_dbkit::{ColumnSpec, TableSpec};
use rusqlite::{Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `node_role_takeovers` table's
/// schema. Its DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "node_role_takeovers",
    comment: Some("Explicit marker that the user has taken over a contributor role."),
    columns: &[
        ColumnSpec::int("node_id").not_null(),
        ColumnSpec::text("role").not_null(),
        ColumnSpec::text("curated_at").not_null(),
        ColumnSpec::text("curated_by").not_null(),
        ColumnSpec::text("notes"),
    ],
    composite_pk: Some(&["node_id", "role"]),
    uniques: &[],
    table_checks: &[],
    indexes: &[],
};

/// Insert or replace one (node, role) takeover marker. `curated_at` is
/// generated by SQLite so the whole crate shares one timestamp source.
const UPSERT_SQL: &str = "INSERT INTO node_role_takeovers \
     (node_id, role, curated_at, curated_by, notes) \
     VALUES (:node_id, :role, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :curated_by, :notes) \
     ON CONFLICT(node_id, role) DO UPDATE SET \
       curated_at = excluded.curated_at, \
       curated_by = excluded.curated_by, \
       notes = excluded.notes";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!(
        "SELECT {} FROM node_role_takeovers {tail}",
        SPEC.select_list()
    )
}

/// One `node_role_takeovers` row — a marker that the user owns one
/// contributor role on one node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeRoleTakeover {
    /// The node whose role was taken over.
    pub node_id: i64,
    /// The taken-over contributor role.
    pub role: String,
    /// When the takeover was last curated, ISO-8601 UTC.
    pub curated_at: String,
    /// Who curated the takeover.
    pub curated_by: String,
    /// Free-form notes.
    pub notes: Option<String>,
}

impl NodeRoleTakeover {
    /// Build a [`NodeRoleTakeover`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<NodeRoleTakeover> {
        Ok(NodeRoleTakeover {
            node_id: row.get("node_id")?,
            role: row.get("role")?,
            curated_at: row.get("curated_at")?,
            curated_by: row.get("curated_by")?,
            notes: row.get("notes")?,
        })
    }
}

/// A role-takeover marker about to be written.
#[derive(Debug, Clone)]
pub struct NewRoleTakeover {
    node_id: i64,
    role: String,
    curated_by: String,
    notes: Option<String>,
}

impl NewRoleTakeover {
    /// A takeover of `role` on `node_id`, note-free until the builder
    /// says otherwise.
    pub fn new(
        node_id: i64,
        role: impl Into<String>,
        curated_by: impl Into<String>,
    ) -> NewRoleTakeover {
        NewRoleTakeover {
            node_id,
            role: role.into(),
            curated_by: curated_by.into(),
            notes: None,
        }
    }

    /// Attach free-form notes.
    pub fn notes(mut self, notes: impl Into<String>) -> NewRoleTakeover {
        self.notes = Some(notes.into());
        self
    }
}

impl Catalog {
    /// Insert or replace one (node, role) takeover marker.
    pub fn mark_role_takeover(&self, new: &NewRoleTakeover) -> Result<()> {
        self.conn.execute(
            UPSERT_SQL,
            named_params! {
                ":node_id": new.node_id,
                ":role": new.role,
                ":curated_by": new.curated_by,
                ":notes": new.notes,
            },
        )?;
        Ok(())
    }

    /// Every role takeover on `node_id`, ordered by role name.
    pub fn role_takeovers_for_node(&self, node_id: i64) -> Result<Vec<NodeRoleTakeover>> {
        let mut stmt = self
            .conn
            .prepare(&select_sql("WHERE node_id = :node_id ORDER BY role"))?;
        let rows = stmt
            .query_map(
                named_params! { ":node_id": node_id },
                NodeRoleTakeover::from_row,
            )?
            .collect::<rusqlite::Result<Vec<NodeRoleTakeover>>>()?;
        Ok(rows)
    }

    /// Remove a role-takeover marker. Returns whether a row existed.
    pub fn clear_role_takeover(&self, node_id: i64, role: &str) -> Result<bool> {
        let affected = self.conn.execute(
            "DELETE FROM node_role_takeovers WHERE node_id = :node_id AND role = :role",
            named_params! { ":node_id": node_id, ":role": role },
        )?;
        Ok(affected > 0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_role_takeover_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .mark_role_takeover(
                &NewRoleTakeover::new(100_000_001, "translator", "human")
                    .notes("cleared a wrong extraction"),
            )
            .expect("write");

        let all = catalog.role_takeovers_for_node(100_000_001).expect("read");
        assert_eq!(all.len(), 1);
        let row = &all[0];
        assert_eq!(row.node_id, 100_000_001);
        assert_eq!(row.role, "translator");
        assert!(!row.curated_at.is_empty());
        assert_eq!(row.curated_by, "human");
        assert_eq!(row.notes.as_deref(), Some("cleared a wrong extraction"));
    }

    #[test]
    fn a_takeover_can_be_marked_and_cleared() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .mark_role_takeover(&NewRoleTakeover::new(100_000_001, "editor", "human"))
            .expect("mark");
        assert!(
            catalog
                .clear_role_takeover(100_000_001, "editor")
                .expect("clear")
        );
        assert!(
            catalog
                .role_takeovers_for_node(100_000_001)
                .expect("read")
                .is_empty()
        );
        assert!(
            !catalog
                .clear_role_takeover(100_000_001, "editor")
                .expect("miss")
        );
    }
}
