// SPDX-License-Identifier: Apache-2.0

//! The `node_role_takeovers` table — explicit role-takeover markers.
//!
//! One row per (node, role) the user has taken over. The marker
//! resolves an ambiguity: an empty list of *user* contributors for a
//! role could mean either "the user has not curated this role" or "the
//! user has deliberately cleared it". A takeover row says it is the
//! latter.

use bookrack_core::ItemKind;
use bookrack_dbkit::{ColumnSpec, TableSpec};
use rusqlite::{Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `node_role_takeovers` table's
/// schema. Its DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "node_role_takeovers",
    comment: Some("Explicit marker that the user has taken over a contributor role."),
    columns: &[
        ColumnSpec::int("intake_id").not_null(),
        ColumnSpec::text("scope").not_null(),
        ColumnSpec::text("role").not_null(),
        ColumnSpec::text("curated_at").not_null(),
        ColumnSpec::text("curated_by").not_null(),
        ColumnSpec::text("notes"),
    ],
    composite_pk: Some(&["intake_id", "scope", "role"]),
    uniques: &[],
    table_checks: &[],
    indexes: &[],
};

/// Insert or replace one (node, role) takeover marker. `curated_at` is
/// generated by SQLite so the whole crate shares one timestamp source.
const UPSERT_SQL: &str = "INSERT INTO node_role_takeovers \
     (intake_id, scope, role, curated_at, curated_by, notes) \
     VALUES (:intake_id, :scope, :role, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), \
             :curated_by, :notes) \
     ON CONFLICT(intake_id, scope, role) DO UPDATE SET \
       curated_at = excluded.curated_at, \
       curated_by = excluded.curated_by, \
       notes = excluded.notes";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!(
        "SELECT {} FROM node_role_takeovers {tail}",
        SPEC.select_list()
    )
}

/// One `node_role_takeovers` row — a marker that the user owns one
/// contributor role on one node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeRoleTakeover {
    /// The book whose node had a role taken over — a soft reference to
    /// the `intake` registry.
    pub intake_id: i64,
    /// The logical address of the node within the book's partition.
    pub scope: String,
    /// The taken-over contributor role.
    pub role: String,
    /// When the takeover was last curated, ISO-8601 UTC.
    pub curated_at: String,
    /// Who curated the takeover.
    pub curated_by: String,
    /// Free-form notes.
    pub notes: Option<String>,
}

impl NodeRoleTakeover {
    /// Build a [`NodeRoleTakeover`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<NodeRoleTakeover> {
        Ok(NodeRoleTakeover {
            intake_id: row.get("intake_id")?,
            scope: row.get("scope")?,
            role: row.get("role")?,
            curated_at: row.get("curated_at")?,
            curated_by: row.get("curated_by")?,
            notes: row.get("notes")?,
        })
    }
}

/// A role-takeover marker about to be written.
#[derive(Debug, Clone)]
pub struct NewRoleTakeover {
    intake_id: i64,
    scope: String,
    role: String,
    curated_by: String,
    notes: Option<String>,
}

impl NewRoleTakeover {
    /// A takeover of `role` on the node at `(intake_id, scope)`, note-free
    /// until the builder says otherwise.
    pub fn new(
        intake_id: i64,
        kind: ItemKind,
        role: impl Into<String>,
        curated_by: impl Into<String>,
    ) -> NewRoleTakeover {
        NewRoleTakeover {
            intake_id,
            scope: kind.as_scope_str().to_string(),
            role: role.into(),
            curated_by: curated_by.into(),
            notes: None,
        }
    }

    /// Attach free-form notes.
    pub fn notes(mut self, notes: impl Into<String>) -> NewRoleTakeover {
        self.notes = Some(notes.into());
        self
    }
}

impl Catalog {
    /// Insert or replace one (node, role) takeover marker.
    pub fn mark_role_takeover(&self, new: &NewRoleTakeover) -> Result<()> {
        self.conn.execute(
            UPSERT_SQL,
            named_params! {
                ":intake_id": new.intake_id,
                ":scope": new.scope,
                ":role": new.role,
                ":curated_by": new.curated_by,
                ":notes": new.notes,
            },
        )?;
        Ok(())
    }

    /// Every role takeover on the node at `(intake_id, scope)`, ordered by
    /// role name.
    pub fn role_takeovers_for_address(
        &self,
        intake_id: i64,
        kind: ItemKind,
    ) -> Result<Vec<NodeRoleTakeover>> {
        let mut stmt = self.conn.prepare(&select_sql(
            "WHERE intake_id = :intake_id AND scope = :scope ORDER BY role",
        ))?;
        let rows = stmt
            .query_map(
                named_params! { ":intake_id": intake_id, ":scope": kind.as_scope_str() },
                NodeRoleTakeover::from_row,
            )?
            .collect::<rusqlite::Result<Vec<NodeRoleTakeover>>>()?;
        Ok(rows)
    }

    /// Remove a role-takeover marker. Returns whether a row existed.
    pub fn clear_role_takeover(&self, intake_id: i64, kind: ItemKind, role: &str) -> Result<bool> {
        let affected = self.conn.execute(
            "DELETE FROM node_role_takeovers \
             WHERE intake_id = :intake_id AND scope = :scope AND role = :role",
            named_params! {
                ":intake_id": intake_id,
                ":scope": kind.as_scope_str(),
                ":role": role,
            },
        )?;
        Ok(affected > 0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The item kind used throughout these tests.
    const KIND: ItemKind = ItemKind::Book;

    #[test]
    fn a_role_takeover_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .mark_role_takeover(
                &NewRoleTakeover::new(1, KIND, "translator", "human")
                    .notes("cleared a wrong extraction"),
            )
            .expect("write");

        let all = catalog.role_takeovers_for_address(1, KIND).expect("read");
        assert_eq!(all.len(), 1);
        let row = &all[0];
        assert_eq!(row.intake_id, 1);
        assert_eq!(row.scope, KIND.as_scope_str());
        assert_eq!(row.role, "translator");
        assert!(!row.curated_at.is_empty());
        assert_eq!(row.curated_by, "human");
        assert_eq!(row.notes.as_deref(), Some("cleared a wrong extraction"));
    }

    #[test]
    fn a_takeover_can_be_marked_and_cleared() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .mark_role_takeover(&NewRoleTakeover::new(1, KIND, "editor", "human"))
            .expect("mark");
        assert!(
            catalog
                .clear_role_takeover(1, KIND, "editor")
                .expect("clear")
        );
        assert!(
            catalog
                .role_takeovers_for_address(1, KIND)
                .expect("read")
                .is_empty()
        );
        assert!(
            !catalog
                .clear_role_takeover(1, KIND, "editor")
                .expect("miss")
        );
    }
}
