// SPDX-License-Identifier: Apache-2.0

//! The `node_reviews` table — per-node review status.
//!
//! One row per reviewed node, recording the outcome of one review
//! pass. The row is keyed by `(intake_id, scope)` and rewritten on
//! each pass. There is no DDL CHECK on `status`; the column carries
//! one of four tokens by convention:
//!
//! - `clean` — every required field is present and clean.
//! - `needs_work` — at least one required field is missing or
//!   flagged. Advisory; does not gate the pipeline.
//! - `acknowledged` — the gap is known and was deliberately let
//!   through (a human signed off via the metadata-ack flow).
//! - `rejected` — a human-level book-wide reject.

use bookrack_dbkit::{ColumnSpec, TableSpec};
use rusqlite::{OptionalExtension, Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `node_reviews` table's schema. Its
/// DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "node_reviews",
    comment: Some("Per-node review status."),
    columns: &[
        ColumnSpec::int("intake_id").not_null(),
        ColumnSpec::text("scope").not_null(),
        ColumnSpec::text("reviewed_at").not_null(),
        ColumnSpec::text("reviewed_by").not_null(),
        ColumnSpec::text("status")
            .not_null()
            .comment("clean / needs_work / acknowledged / rejected"),
        ColumnSpec::text("notes"),
    ],
    composite_pk: Some(&["intake_id", "scope"]),
    uniques: &[],
    table_checks: &[],
    indexes: &[],
};

/// Insert or replace a node's review, keyed by `node_id`. `reviewed_at`
/// is generated by SQLite so the whole crate shares one timestamp source.
const UPSERT_SQL: &str = "INSERT INTO node_reviews \
     (intake_id, scope, reviewed_at, reviewed_by, status, notes) \
     VALUES (:intake_id, :scope, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), \
             :reviewed_by, :status, :notes) \
     ON CONFLICT(intake_id, scope) DO UPDATE SET \
       reviewed_at = excluded.reviewed_at, \
       reviewed_by = excluded.reviewed_by, \
       status = excluded.status, \
       notes = excluded.notes";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM node_reviews {tail}", SPEC.select_list())
}

/// One `node_reviews` row — the outcome of one node's review.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeReview {
    /// The book whose node was reviewed — a soft reference to the
    /// `intake` registry.
    pub intake_id: i64,
    /// The logical address of the node within the book's partition.
    pub scope: String,
    /// When the review was made, ISO-8601 UTC.
    pub reviewed_at: String,
    /// Who made the review.
    pub reviewed_by: String,
    /// The review outcome (`clean` / `needs_work` / `rejected`).
    pub status: String,
    /// Free-form notes.
    pub notes: Option<String>,
}

impl NodeReview {
    /// Build a [`NodeReview`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<NodeReview> {
        Ok(NodeReview {
            intake_id: row.get("intake_id")?,
            scope: row.get("scope")?,
            reviewed_at: row.get("reviewed_at")?,
            reviewed_by: row.get("reviewed_by")?,
            status: row.get("status")?,
            notes: row.get("notes")?,
        })
    }
}

/// A review about to be written.
#[derive(Debug, Clone)]
pub struct NewReview {
    intake_id: i64,
    scope: String,
    reviewed_by: String,
    status: String,
    notes: Option<String>,
}

impl NewReview {
    /// A review of the node at `(intake_id, scope)` with the given
    /// outcome, note-free until the builder says otherwise.
    pub fn new(
        intake_id: i64,
        scope: impl Into<String>,
        reviewed_by: impl Into<String>,
        status: impl Into<String>,
    ) -> NewReview {
        NewReview {
            intake_id,
            scope: scope.into(),
            reviewed_by: reviewed_by.into(),
            status: status.into(),
            notes: None,
        }
    }

    /// Attach free-form notes.
    pub fn notes(mut self, notes: impl Into<String>) -> NewReview {
        self.notes = Some(notes.into());
        self
    }
}

impl Catalog {
    /// Insert or replace a node's review.
    pub fn upsert_review(&self, new: &NewReview) -> Result<()> {
        self.conn.execute(
            UPSERT_SQL,
            named_params! {
                ":intake_id": new.intake_id,
                ":scope": new.scope,
                ":reviewed_by": new.reviewed_by,
                ":status": new.status,
                ":notes": new.notes,
            },
        )?;
        Ok(())
    }

    /// Fetch the review of the node at `(intake_id, scope)`, or `None` if
    /// it has not been reviewed.
    pub fn review(&self, intake_id: i64, scope: &str) -> Result<Option<NodeReview>> {
        let review = self
            .conn
            .query_row(
                &select_sql("WHERE intake_id = :intake_id AND scope = :scope"),
                named_params! { ":intake_id": intake_id, ":scope": scope },
                NodeReview::from_row,
            )
            .optional()?;
        Ok(review)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A logical address used throughout these tests.
    const SCOPE: &str = "book";

    #[test]
    fn a_review_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .upsert_review(&NewReview::new(1, SCOPE, "human", "needs_work").notes("check the TOC"))
            .expect("write");

        let read = catalog.review(1, SCOPE).expect("read").expect("present");
        assert_eq!(read.intake_id, 1);
        assert_eq!(read.scope, SCOPE);
        assert!(!read.reviewed_at.is_empty());
        assert_eq!(read.reviewed_by, "human");
        assert_eq!(read.status, "needs_work");
        assert_eq!(read.notes.as_deref(), Some("check the TOC"));
    }

    #[test]
    fn a_missing_review_reads_as_none() {
        let catalog = Catalog::open_in_memory().expect("open");
        assert!(catalog.review(404, SCOPE).expect("read").is_none());
    }

    #[test]
    fn upsert_overwrites_a_previous_review() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .upsert_review(&NewReview::new(1, SCOPE, "human", "needs_work"))
            .expect("first review");
        catalog
            .upsert_review(&NewReview::new(1, SCOPE, "human", "clean"))
            .expect("second review");
        let read = catalog.review(1, SCOPE).expect("read").expect("present");
        assert_eq!(read.status, "clean");
    }
}
