// SPDX-License-Identifier: Apache-2.0

//! The `node_overrides` table — user corrections to the metadata base
//! layer.
//!
//! An entity-attribute-value table: one row per (node, field) the user
//! has overridden. A field has three states — *absent* (no row, the base
//! layer stands), *a value*, or an *explicit NULL* (a deliberate
//! nullify). The effective-metadata merge applies these on top of
//! `node_publication_attrs`.

use bookrack_dbkit::{ColumnSpec, TableSpec};
use rusqlite::{Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `node_overrides` table's schema.
/// Its DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "node_overrides",
    comment: Some("User EAV edits overriding the metadata base layer."),
    columns: &[
        ColumnSpec::int("intake_id").not_null(),
        ColumnSpec::text("scope").not_null(),
        ColumnSpec::text("field").not_null(),
        ColumnSpec::text("value")
            .comment("a value, or an explicit NULL meaning deliberate nullify"),
        ColumnSpec::int("confirmed").not_null().default("0"),
        ColumnSpec::text("curated_at").not_null(),
        ColumnSpec::text("curated_by").not_null(),
        ColumnSpec::text("notes"),
    ],
    composite_pk: Some(&["intake_id", "scope", "field"]),
    uniques: &[],
    table_checks: &[],
    indexes: &[],
};

/// Insert or replace one (node, field) override, keyed by the composite
/// primary key. `curated_at` is generated by SQLite so the whole crate
/// shares one timestamp source.
const UPSERT_SQL: &str = "INSERT INTO node_overrides \
     (intake_id, scope, field, value, confirmed, curated_at, curated_by, notes) \
     VALUES (:intake_id, :scope, :field, :value, :confirmed, \
             strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :curated_by, :notes) \
     ON CONFLICT(intake_id, scope, field) DO UPDATE SET \
       value = excluded.value, \
       confirmed = excluded.confirmed, \
       curated_at = excluded.curated_at, \
       curated_by = excluded.curated_by, \
       notes = excluded.notes";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM node_overrides {tail}", SPEC.select_list())
}

/// One `node_overrides` row — a user's override of a single metadata
/// field on one node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeOverride {
    /// The book whose node is overridden — a soft reference to the
    /// `intake` registry.
    pub intake_id: i64,
    /// The logical address of the node within the book's partition.
    pub scope: String,
    /// The metadata field being overridden.
    pub field: String,
    /// The override value. `None` is a *deliberate nullify*, distinct
    /// from the field having no override row at all.
    pub value: Option<String>,
    /// Whether the user has confirmed this override.
    pub confirmed: bool,
    /// When the override was last curated, ISO-8601 UTC.
    pub curated_at: String,
    /// Who curated the override.
    pub curated_by: String,
    /// Free-form notes.
    pub notes: Option<String>,
}

impl NodeOverride {
    /// Build a [`NodeOverride`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<NodeOverride> {
        Ok(NodeOverride {
            intake_id: row.get("intake_id")?,
            scope: row.get("scope")?,
            field: row.get("field")?,
            value: row.get("value")?,
            confirmed: row.get("confirmed")?,
            curated_at: row.get("curated_at")?,
            curated_by: row.get("curated_by")?,
            notes: row.get("notes")?,
        })
    }
}

/// An override about to be written.
///
/// `value` is taken explicitly as an `Option` at construction so the
/// *value* and *deliberate nullify* states cannot be confused with a
/// forgotten field.
#[derive(Debug, Clone)]
pub struct NewOverride {
    intake_id: i64,
    scope: String,
    field: String,
    value: Option<String>,
    confirmed: bool,
    curated_by: String,
    notes: Option<String>,
}

impl NewOverride {
    /// An override of `field` on the node at `(intake_id, scope)`. Pass
    /// `Some` for a value or `None` for a deliberate nullify. Unconfirmed
    /// and note-free until the builder methods say otherwise.
    pub fn new(
        intake_id: i64,
        scope: impl Into<String>,
        field: impl Into<String>,
        value: Option<String>,
        curated_by: impl Into<String>,
    ) -> NewOverride {
        NewOverride {
            intake_id,
            scope: scope.into(),
            field: field.into(),
            value,
            confirmed: false,
            curated_by: curated_by.into(),
            notes: None,
        }
    }

    /// Mark the override confirmed (or not).
    pub fn confirmed(mut self, confirmed: bool) -> NewOverride {
        self.confirmed = confirmed;
        self
    }

    /// Attach free-form notes.
    pub fn notes(mut self, notes: impl Into<String>) -> NewOverride {
        self.notes = Some(notes.into());
        self
    }
}

impl Catalog {
    /// Insert or replace one (node, field) override.
    pub fn set_override(&self, new: &NewOverride) -> Result<()> {
        self.conn.execute(
            UPSERT_SQL,
            named_params! {
                ":intake_id": new.intake_id,
                ":scope": new.scope,
                ":field": new.field,
                ":value": new.value,
                ":confirmed": new.confirmed,
                ":curated_by": new.curated_by,
                ":notes": new.notes,
            },
        )?;
        Ok(())
    }

    /// Every override on the node at `(intake_id, scope)`, ordered by
    /// field name.
    pub fn overrides_for_address(&self, intake_id: i64, scope: &str) -> Result<Vec<NodeOverride>> {
        let mut stmt = self.conn.prepare(&select_sql(
            "WHERE intake_id = :intake_id AND scope = :scope ORDER BY field",
        ))?;
        let rows = stmt
            .query_map(
                named_params! { ":intake_id": intake_id, ":scope": scope },
                NodeOverride::from_row,
            )?
            .collect::<rusqlite::Result<Vec<NodeOverride>>>()?;
        Ok(rows)
    }

    /// Remove an override, returning the field to its *absent* state.
    /// Returns whether a row existed.
    pub fn clear_override(&self, intake_id: i64, scope: &str, field: &str) -> Result<bool> {
        let affected = self.conn.execute(
            "DELETE FROM node_overrides \
             WHERE intake_id = :intake_id AND scope = :scope AND field = :field",
            named_params! { ":intake_id": intake_id, ":scope": scope, ":field": field },
        )?;
        Ok(affected > 0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A logical address used throughout these tests.
    const SCOPE: &str = "book";

    #[test]
    fn an_override_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .set_override(
                &NewOverride::new(1, SCOPE, "title", Some("Corrected".into()), "human")
                    .confirmed(true)
                    .notes("fixed a typo"),
            )
            .expect("write");

        let all = catalog.overrides_for_address(1, SCOPE).expect("read");
        assert_eq!(all.len(), 1);
        let row = &all[0];
        assert_eq!(row.intake_id, 1);
        assert_eq!(row.scope, SCOPE);
        assert_eq!(row.field, "title");
        assert_eq!(row.value.as_deref(), Some("Corrected"));
        assert!(row.confirmed);
        assert!(!row.curated_at.is_empty());
        assert_eq!(row.curated_by, "human");
        assert_eq!(row.notes.as_deref(), Some("fixed a typo"));
    }

    #[test]
    fn an_explicit_null_is_distinct_from_an_absent_override() {
        let catalog = Catalog::open_in_memory().expect("open");
        // A deliberate nullify: a row exists, but its value is NULL.
        catalog
            .set_override(&NewOverride::new(1, SCOPE, "subtitle", None, "human"))
            .expect("write");

        let all = catalog.overrides_for_address(1, SCOPE).expect("read");
        assert_eq!(all.len(), 1, "the nullify is a real row");
        assert_eq!(all[0].value, None);
        // A field with no row at all is simply absent.
        assert!(all.iter().all(|o| o.field != "publisher"));
    }

    #[test]
    fn set_override_replaces_and_clear_override_removes() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .set_override(&NewOverride::new(
                1,
                SCOPE,
                "title",
                Some("First".into()),
                "human",
            ))
            .expect("first");
        catalog
            .set_override(&NewOverride::new(
                1,
                SCOPE,
                "title",
                Some("Second".into()),
                "human",
            ))
            .expect("replace");
        let all = catalog.overrides_for_address(1, SCOPE).expect("read");
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].value.as_deref(), Some("Second"));

        assert!(catalog.clear_override(1, SCOPE, "title").expect("clear"));
        assert!(
            catalog
                .overrides_for_address(1, SCOPE)
                .expect("read")
                .is_empty()
        );
        // Clearing an absent override is a harmless miss.
        assert!(!catalog.clear_override(1, SCOPE, "title").expect("miss"));
    }
}
