// SPDX-License-Identifier: Apache-2.0

//! The `node_reviews` table — per-node review status.
//!
//! One row per reviewed node, keyed by `(intake_id, scope)` and rewritten
//! on each pass.
//!
//! Status is **strictly a human/LLM judgement**. The audit's plausibility
//! verdict lives elsewhere (`node_publication_attrs.confidence` and the
//! per-field grades returned from [`bookrack_metadata::audit`]). The
//! audit can flag a record as `low` confidence, but it can never declare
//! the record reviewed: only a human or an LLM acting on a human's
//! behalf can advance status away from [`STATUS_PENDING`]. Metadata
//! correctness is irreducibly a human concern — no extractor or
//! heuristic can promise it — so the table keeps the two axes apart.
//!
//! `reviewed_by` carries a `<namespace>:<id>` token by convention. The
//! ingest pipeline writes `bookrack-ingest:<profile-name>` (e.g.
//! `bookrack-ingest:default` or `bookrack-ingest:trust-source`) so a
//! query can tell apart the audit-profile flavours of a `pending` row.
//! Human and LLM advancers overwrite this column with their own
//! namespaced token (`human:<email>`, `llm:<model>@<version>`).
//!
//! There is no DDL CHECK on `status`; the column carries one of four
//! tokens by convention:
//!
//! - [`STATUS_PENDING`] `pending` — the pipeline inserts this on every
//!   fresh ingest. It means "no human/LLM has confirmed this record".
//! - [`STATUS_APPROVED`] `approved` — a human/LLM read the record and
//!   confirmed the metadata is correct.
//! - [`STATUS_ACKNOWLEDGED`] `acknowledged` — a human/LLM looked at an
//!   audit-flagged gap and decided to let it through anyway (the
//!   `metadata ack` flow).
//! - [`STATUS_REJECTED`] `rejected` — a human/LLM rejected the book
//!   outright.

use bookrack_dbkit::{ColumnSpec, TableSpec};
use rusqlite::{OptionalExtension, Row, named_params};

use crate::{Catalog, Result};

/// `node_reviews.status` value the pipeline writes after a fresh ingest.
/// Means "no human or LLM has confirmed this record". The pipeline never
/// writes any other value.
pub const STATUS_PENDING: &str = "pending";

/// `node_reviews.status` value a human or LLM writes when the metadata
/// has been read and confirmed correct.
pub const STATUS_APPROVED: &str = "approved";

/// `node_reviews.status` value a human or LLM writes when an audit gap
/// is known and deliberately let through (the `metadata ack` flow).
pub const STATUS_ACKNOWLEDGED: &str = "acknowledged";

/// `node_reviews.status` value a human or LLM writes when the book is
/// rejected outright.
pub const STATUS_REJECTED: &str = "rejected";

/// The single source of truth for the `node_reviews` table's schema. Its
/// DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "node_reviews",
    comment: Some("Per-node review status."),
    columns: &[
        ColumnSpec::int("intake_id").not_null(),
        ColumnSpec::text("scope").not_null(),
        ColumnSpec::text("reviewed_at").not_null(),
        ColumnSpec::text("reviewed_by").not_null(),
        ColumnSpec::text("status")
            .not_null()
            .comment("pending / approved / acknowledged / rejected"),
        ColumnSpec::text("notes"),
    ],
    composite_pk: Some(&["intake_id", "scope"]),
    uniques: &[],
    table_checks: &[],
    indexes: &[],
};

/// Insert or replace a node's review, keyed by `node_id`. `reviewed_at`
/// is generated by SQLite so the whole crate shares one timestamp source.
const UPSERT_SQL: &str = "INSERT INTO node_reviews \
     (intake_id, scope, reviewed_at, reviewed_by, status, notes) \
     VALUES (:intake_id, :scope, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), \
             :reviewed_by, :status, :notes) \
     ON CONFLICT(intake_id, scope) DO UPDATE SET \
       reviewed_at = excluded.reviewed_at, \
       reviewed_by = excluded.reviewed_by, \
       status = excluded.status, \
       notes = excluded.notes";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM node_reviews {tail}", SPEC.select_list())
}

/// One `node_reviews` row — the outcome of one node's review.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeReview {
    /// The book whose node was reviewed — a soft reference to the
    /// `intake` registry.
    pub intake_id: i64,
    /// The logical address of the node within the book's partition.
    pub scope: String,
    /// When the review was made, ISO-8601 UTC.
    pub reviewed_at: String,
    /// Who made the review.
    pub reviewed_by: String,
    /// The review outcome (`pending` / `approved` / `acknowledged` /
    /// `rejected`). See the module-level documentation.
    pub status: String,
    /// Free-form notes.
    pub notes: Option<String>,
}

impl NodeReview {
    /// Build a [`NodeReview`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<NodeReview> {
        Ok(NodeReview {
            intake_id: row.get("intake_id")?,
            scope: row.get("scope")?,
            reviewed_at: row.get("reviewed_at")?,
            reviewed_by: row.get("reviewed_by")?,
            status: row.get("status")?,
            notes: row.get("notes")?,
        })
    }
}

/// A review about to be written.
#[derive(Debug, Clone)]
pub struct NewReview {
    intake_id: i64,
    scope: String,
    reviewed_by: String,
    status: String,
    notes: Option<String>,
}

impl NewReview {
    /// A review of the node at `(intake_id, scope)` with the given
    /// outcome, note-free until the builder says otherwise.
    pub fn new(
        intake_id: i64,
        scope: impl Into<String>,
        reviewed_by: impl Into<String>,
        status: impl Into<String>,
    ) -> NewReview {
        NewReview {
            intake_id,
            scope: scope.into(),
            reviewed_by: reviewed_by.into(),
            status: status.into(),
            notes: None,
        }
    }

    /// Attach free-form notes.
    pub fn notes(mut self, notes: impl Into<String>) -> NewReview {
        self.notes = Some(notes.into());
        self
    }
}

impl Catalog {
    /// Insert or replace a node's review.
    pub fn upsert_review(&self, new: &NewReview) -> Result<()> {
        self.conn.execute(
            UPSERT_SQL,
            named_params! {
                ":intake_id": new.intake_id,
                ":scope": new.scope,
                ":reviewed_by": new.reviewed_by,
                ":status": new.status,
                ":notes": new.notes,
            },
        )?;
        Ok(())
    }

    /// Fetch the review of the node at `(intake_id, scope)`, or `None` if
    /// it has not been reviewed.
    pub fn review(&self, intake_id: i64, scope: &str) -> Result<Option<NodeReview>> {
        let review = self
            .conn
            .query_row(
                &select_sql("WHERE intake_id = :intake_id AND scope = :scope"),
                named_params! { ":intake_id": intake_id, ":scope": scope },
                NodeReview::from_row,
            )
            .optional()?;
        Ok(review)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A logical address used throughout these tests.
    const SCOPE: &str = "book";

    #[test]
    fn a_review_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .upsert_review(
                &NewReview::new(1, SCOPE, "human", STATUS_ACKNOWLEDGED).notes("check the TOC"),
            )
            .expect("write");

        let read = catalog.review(1, SCOPE).expect("read").expect("present");
        assert_eq!(read.intake_id, 1);
        assert_eq!(read.scope, SCOPE);
        assert!(!read.reviewed_at.is_empty());
        assert_eq!(read.reviewed_by, "human");
        assert_eq!(read.status, STATUS_ACKNOWLEDGED);
        assert_eq!(read.notes.as_deref(), Some("check the TOC"));
    }

    #[test]
    fn a_missing_review_reads_as_none() {
        let catalog = Catalog::open_in_memory().expect("open");
        assert!(catalog.review(404, SCOPE).expect("read").is_none());
    }

    #[test]
    fn upsert_overwrites_a_previous_review() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .upsert_review(&NewReview::new(1, SCOPE, "human", STATUS_PENDING))
            .expect("first review");
        catalog
            .upsert_review(&NewReview::new(1, SCOPE, "human", STATUS_APPROVED))
            .expect("second review");
        let read = catalog.review(1, SCOPE).expect("read").expect("present");
        assert_eq!(read.status, STATUS_APPROVED);
    }
}
