// SPDX-License-Identifier: Apache-2.0

//! The `retrieval_issues` table — retrieval-quality issue reports.
//!
//! One row per reported retrieval problem (a recall miss, a zero-hit
//! query, a wrong-volume hit), with the query that triggered it and a
//! triage lifecycle. It is an observability table — diagnostic,
//! trimmable, never a source of truth.

use bookrack_dbkit::{ColumnSpec, IndexSpec, TableSpec};
use rusqlite::{OptionalExtension, Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `retrieval_issues` table's schema.
/// Its DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "retrieval_issues",
    comment: Some("Observability: retrieval-quality issue reports."),
    columns: &[
        ColumnSpec::int("issue_id").pk_autoinc(),
        ColumnSpec::text("created_at").not_null(),
        ColumnSpec::text("updated_at").not_null(),
        ColumnSpec::text("status")
            .not_null()
            .default("'open'")
            .comment("open / triaged / resolved / wontfix"),
        ColumnSpec::text("kind")
            .not_null()
            .comment("recall_miss / zero_hits / wrong_volume / ..."),
        ColumnSpec::text("severity").not_null().default("'medium'"),
        ColumnSpec::text("query"),
        ColumnSpec::text("query_hash"),
        ColumnSpec::text("mode"),
        ColumnSpec::text("filters_json"),
        ColumnSpec::text("expected"),
        ColumnSpec::text("observed"),
        ColumnSpec::text("suspected_book"),
        ColumnSpec::text("agent_notes"),
        ColumnSpec::int("seen_count").not_null().default("1"),
        ColumnSpec::text("resolution"),
        ColumnSpec::text("resolved_at"),
    ],
    composite_pk: None,
    uniques: &[],
    table_checks: &[],
    indexes: &[
        IndexSpec::on("idx_issues_status", &["status", "created_at"]),
        IndexSpec::on("idx_issues_dedup", &["query_hash"]).partial("status = 'open'"),
    ],
};

/// Insert one issue and return its surrogate id. `created_at` and
/// `updated_at` are generated by SQLite so the whole crate shares one
/// timestamp source.
const INSERT_SQL: &str = "INSERT INTO retrieval_issues \
     (created_at, updated_at, status, kind, severity, query, query_hash, mode, \
      filters_json, expected, observed, suspected_book, agent_notes, seen_count, \
      resolution, resolved_at) \
     VALUES (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), \
             strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :status, :kind, :severity, \
             :query, :query_hash, :mode, :filters_json, :expected, :observed, \
             :suspected_book, :agent_notes, :seen_count, :resolution, :resolved_at) \
     RETURNING issue_id";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM retrieval_issues {tail}", SPEC.select_list())
}

/// One `retrieval_issues` row — a single retrieval-quality report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RetrievalIssue {
    /// Surrogate key, assigned by the database.
    pub issue_id: i64,
    /// When the issue was first reported, ISO-8601 UTC.
    pub created_at: String,
    /// When the issue was last touched, ISO-8601 UTC.
    pub updated_at: String,
    /// Triage state (`open` / `triaged` / `resolved` / `wontfix`).
    pub status: String,
    /// What kind of problem it is (`recall_miss` / `zero_hits` / ...).
    pub kind: String,
    /// How bad it is.
    pub severity: String,
    /// The query that triggered the issue.
    pub query: Option<String>,
    /// A hash of the query, used to deduplicate open issues.
    pub query_hash: Option<String>,
    /// The retrieval mode in use.
    pub mode: Option<String>,
    /// The active filters, as JSON.
    pub filters_json: Option<String>,
    /// What the reporter expected to find.
    pub expected: Option<String>,
    /// What was actually returned.
    pub observed: Option<String>,
    /// The book the reporter suspects is involved.
    pub suspected_book: Option<String>,
    /// Free-form notes from the reporting agent.
    pub agent_notes: Option<String>,
    /// How many times this issue has been seen.
    pub seen_count: i64,
    /// How the issue was resolved, once it is.
    pub resolution: Option<String>,
    /// When the issue was resolved, ISO-8601 UTC.
    pub resolved_at: Option<String>,
}

impl RetrievalIssue {
    /// Build a [`RetrievalIssue`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<RetrievalIssue> {
        Ok(RetrievalIssue {
            issue_id: row.get("issue_id")?,
            created_at: row.get("created_at")?,
            updated_at: row.get("updated_at")?,
            status: row.get("status")?,
            kind: row.get("kind")?,
            severity: row.get("severity")?,
            query: row.get("query")?,
            query_hash: row.get("query_hash")?,
            mode: row.get("mode")?,
            filters_json: row.get("filters_json")?,
            expected: row.get("expected")?,
            observed: row.get("observed")?,
            suspected_book: row.get("suspected_book")?,
            agent_notes: row.get("agent_notes")?,
            seen_count: row.get("seen_count")?,
            resolution: row.get("resolution")?,
            resolved_at: row.get("resolved_at")?,
        })
    }
}

/// An issue about to be written. The surrogate `issue_id` and the
/// `created_at` / `updated_at` timestamps are assigned by the database.
/// The row is a flat record written as a unit, so its fields are public;
/// [`NewRetrievalIssue::new`] sets the mandatory `kind` and applies the
/// same defaults the table's DDL declares for `status`, `severity`, and
/// `seen_count`.
#[derive(Debug, Clone)]
pub struct NewRetrievalIssue {
    /// Triage state; starts at `open`.
    pub status: String,
    /// What kind of problem it is.
    pub kind: String,
    /// How bad it is; starts at `medium`.
    pub severity: String,
    /// The query that triggered the issue.
    pub query: Option<String>,
    /// A hash of the query.
    pub query_hash: Option<String>,
    /// The retrieval mode in use.
    pub mode: Option<String>,
    /// The active filters, as JSON.
    pub filters_json: Option<String>,
    /// What the reporter expected to find.
    pub expected: Option<String>,
    /// What was actually returned.
    pub observed: Option<String>,
    /// The book the reporter suspects is involved.
    pub suspected_book: Option<String>,
    /// Free-form notes from the reporting agent.
    pub agent_notes: Option<String>,
    /// How many times this issue has been seen; starts at 1.
    pub seen_count: i64,
    /// How the issue was resolved.
    pub resolution: Option<String>,
    /// When the issue was resolved, ISO-8601 UTC.
    pub resolved_at: Option<String>,
}

impl NewRetrievalIssue {
    /// A freshly reported issue of `kind`: `open`, `medium` severity,
    /// seen once, with every optional field cleared.
    pub fn new(kind: impl Into<String>) -> NewRetrievalIssue {
        NewRetrievalIssue {
            status: "open".to_string(),
            kind: kind.into(),
            severity: "medium".to_string(),
            query: None,
            query_hash: None,
            mode: None,
            filters_json: None,
            expected: None,
            observed: None,
            suspected_book: None,
            agent_notes: None,
            seen_count: 1,
            resolution: None,
            resolved_at: None,
        }
    }
}

impl Catalog {
    /// Append one row to the retrieval-issue log, returning its
    /// `issue_id`.
    pub fn record_retrieval_issue(&self, new: &NewRetrievalIssue) -> Result<i64> {
        let id = self.conn.query_row(
            INSERT_SQL,
            named_params! {
                ":status": new.status,
                ":kind": new.kind,
                ":severity": new.severity,
                ":query": new.query,
                ":query_hash": new.query_hash,
                ":mode": new.mode,
                ":filters_json": new.filters_json,
                ":expected": new.expected,
                ":observed": new.observed,
                ":suspected_book": new.suspected_book,
                ":agent_notes": new.agent_notes,
                ":seen_count": new.seen_count,
                ":resolution": new.resolution,
                ":resolved_at": new.resolved_at,
            },
            |row| row.get(0),
        )?;
        Ok(id)
    }

    /// Fetch one issue by its id, or `None` if there is no such issue.
    pub fn retrieval_issue(&self, issue_id: i64) -> Result<Option<RetrievalIssue>> {
        let issue = self
            .conn
            .query_row(
                &select_sql("WHERE issue_id = :issue_id"),
                named_params! { ":issue_id": issue_id },
                RetrievalIssue::from_row,
            )
            .optional()?;
        Ok(issue)
    }

    /// Every still-open issue, oldest first.
    pub fn open_retrieval_issues(&self) -> Result<Vec<RetrievalIssue>> {
        let mut stmt = self.conn.prepare(&select_sql(
            "WHERE status = 'open' ORDER BY created_at, issue_id",
        ))?;
        let rows = stmt
            .query_map([], RetrievalIssue::from_row)?
            .collect::<rusqlite::Result<Vec<RetrievalIssue>>>()?;
        Ok(rows)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A `NewRetrievalIssue` with every field set away from its default,
    /// so a dropped column or unbound parameter fails an assertion.
    fn fully_populated() -> NewRetrievalIssue {
        let mut issue = NewRetrievalIssue::new("recall_miss");
        issue.status = "resolved".to_string();
        issue.severity = "high".to_string();
        issue.query = Some("a missing passage".into());
        issue.query_hash = Some("hash-1".into());
        issue.mode = Some("hybrid".into());
        issue.filters_json = Some(r#"{"lang":"en"}"#.into());
        issue.expected = Some("chapter 3".into());
        issue.observed = Some("nothing".into());
        issue.suspected_book = Some("book-7".into());
        issue.agent_notes = Some("likely a chunking gap".into());
        issue.seen_count = 4;
        issue.resolution = Some("reindexed the book".into());
        issue.resolved_at = Some("2026-01-02T00:00:00Z".into());
        issue
    }

    #[test]
    fn a_retrieval_issue_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        let id = catalog
            .record_retrieval_issue(&fully_populated())
            .expect("record");
        assert!(id > 0);

        let read = catalog.retrieval_issue(id).expect("read").expect("present");
        assert_eq!(read.issue_id, id);
        assert!(!read.created_at.is_empty());
        assert!(!read.updated_at.is_empty());
        assert_eq!(read.status, "resolved");
        assert_eq!(read.kind, "recall_miss");
        assert_eq!(read.severity, "high");
        assert_eq!(read.query.as_deref(), Some("a missing passage"));
        assert_eq!(read.query_hash.as_deref(), Some("hash-1"));
        assert_eq!(read.mode.as_deref(), Some("hybrid"));
        assert_eq!(read.filters_json.as_deref(), Some(r#"{"lang":"en"}"#));
        assert_eq!(read.expected.as_deref(), Some("chapter 3"));
        assert_eq!(read.observed.as_deref(), Some("nothing"));
        assert_eq!(read.suspected_book.as_deref(), Some("book-7"));
        assert_eq!(read.agent_notes.as_deref(), Some("likely a chunking gap"));
        assert_eq!(read.seen_count, 4);
        assert_eq!(read.resolution.as_deref(), Some("reindexed the book"));
        assert_eq!(read.resolved_at.as_deref(), Some("2026-01-02T00:00:00Z"));
    }

    #[test]
    fn a_fresh_issue_carries_the_declared_defaults() {
        let catalog = Catalog::open_in_memory().expect("open");
        let id = catalog
            .record_retrieval_issue(&NewRetrievalIssue::new("zero_hits"))
            .expect("record");
        let read = catalog.retrieval_issue(id).expect("read").expect("present");
        assert_eq!(read.status, "open");
        assert_eq!(read.severity, "medium");
        assert_eq!(read.seen_count, 1);
    }

    #[test]
    fn open_issues_exclude_the_resolved_ones() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .record_retrieval_issue(&NewRetrievalIssue::new("zero_hits"))
            .expect("open issue");
        let mut resolved = NewRetrievalIssue::new("recall_miss");
        resolved.status = "resolved".to_string();
        catalog
            .record_retrieval_issue(&resolved)
            .expect("resolved issue");

        let open = catalog.open_retrieval_issues().expect("read");
        assert_eq!(open.len(), 1);
        assert_eq!(open[0].kind, "zero_hits");
    }
}
