// SPDX-License-Identifier: Apache-2.0

//! The `retrieval_calls` table — the retrieval sidecar of
//! `mcp_tool_calls`.
//!
//! One row per retrieval invocation (`search` / `retrieve`), keyed by
//! the same `call_id` as the `mcp_tool_calls` row it was logged under.
//! It captures what the generic tool-call log cannot: the corpus
//! fingerprint the call was served against, the requested depth, and
//! the hit count, with the per-hit detail in `retrieval_call_hits`.
//! A replay window over one corpus state is
//! `WHERE corpus_fingerprint = ?` ordered by `recorded_at`.
//!
//! Like its parent, it is an observability table — diagnostic,
//! trimmable, never a source of truth.

use bookrack_dbkit::{ColumnSpec, ForeignKey, IndexSpec, OnDelete, TableSpec};
use rusqlite::{Connection, OptionalExtension, Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `retrieval_calls` table's schema.
/// Its DDL is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "retrieval_calls",
    comment: Some(
        "Observability: retrieval sidecar of mcp_tool_calls, one row per search / retrieve call.",
    ),
    columns: &[
        ColumnSpec::int("call_id")
            .primary_key()
            .references(ForeignKey::new(
                "mcp_tool_calls",
                "call_id",
                OnDelete::Cascade,
            ))
            .comment("same id as the mcp_tool_calls row the call was logged under"),
        ColumnSpec::text("corpus_fingerprint")
            .not_null()
            .comment("16-hex SHA-256 prefix over the five corpus stamps"),
        ColumnSpec::int("top_k_requested").not_null(),
        ColumnSpec::int("n_hits").not_null(),
        ColumnSpec::text("query_text")
            .comment("copy of the query inside mcp_tool_calls.args, for LIKE filtering"),
        ColumnSpec::text("recorded_at")
            .not_null()
            .comment("ISO-8601 UTC"),
    ],
    composite_pk: None,
    uniques: &[],
    table_checks: &[],
    indexes: &[IndexSpec::on(
        "idx_retrieval_calls_fp_ts",
        &["corpus_fingerprint", "recorded_at"],
    )],
};

/// Insert one `retrieval_calls` row. `recorded_at` is generated by
/// SQLite so the whole crate shares one timestamp source.
const INSERT_SQL: &str = "INSERT INTO retrieval_calls \
     (call_id, corpus_fingerprint, top_k_requested, n_hits, query_text, recorded_at) \
     VALUES (:call_id, :corpus_fingerprint, :top_k_requested, :n_hits, :query_text, \
             strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM retrieval_calls {tail}", SPEC.select_list())
}

/// The retrieval payload of one tool call, about to be written
/// alongside its `mcp_tool_calls` row via
/// [`Catalog::record_tool_call_with_retrieval`]. The shared `call_id`
/// and the `recorded_at` timestamp are assigned at insert; `n_hits` is
/// derived from `hits`.
#[derive(Debug, Clone)]
pub struct NewRetrievalCall {
    /// 16-hex prefix naming the corpus state that served the call.
    pub fingerprint: String,
    /// How many hits the caller asked for.
    pub top_k: i64,
    /// The query text, when the caller passed one along.
    pub query_text: Option<String>,
    /// `(passage_id, distance)` pairs in rank order.
    pub hits: Vec<(String, f32)>,
}

/// Insert one `retrieval_calls` row on `conn`, which may be inside a
/// transaction; the caller owns the commit boundary.
pub(crate) fn insert_retrieval_call(
    conn: &Connection,
    call_id: i64,
    retrieval: &NewRetrievalCall,
) -> rusqlite::Result<()> {
    conn.execute(
        INSERT_SQL,
        named_params! {
            ":call_id": call_id,
            ":corpus_fingerprint": retrieval.fingerprint,
            ":top_k_requested": retrieval.top_k,
            ":n_hits": retrieval.hits.len() as i64,
            ":query_text": retrieval.query_text,
        },
    )?;
    Ok(())
}

/// One retrieval call joined with the `mcp_tool_calls` row it was
/// logged under — the operator-facing listing shape.
#[derive(Debug, Clone, PartialEq)]
pub struct RetrievalCallListing {
    /// The shared call id.
    pub call_id: i64,
    /// When the call was logged, ISO-8601 UTC (from the log row).
    pub ts: String,
    /// The invoked tool (from the log row).
    pub tool: String,
    /// 16-hex prefix naming the corpus state that served the call.
    pub corpus_fingerprint: String,
    /// How many hits the caller asked for.
    pub top_k_requested: i64,
    /// How many hits actually came back.
    pub n_hits: i64,
    /// The query text, when the caller passed one along.
    pub query_text: Option<String>,
}

impl RetrievalCallListing {
    /// Build a [`RetrievalCallListing`] from a joined row.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<RetrievalCallListing> {
        Ok(RetrievalCallListing {
            call_id: row.get("call_id")?,
            ts: row.get("ts")?,
            tool: row.get("tool")?,
            corpus_fingerprint: row.get("corpus_fingerprint")?,
            top_k_requested: row.get("top_k_requested")?,
            n_hits: row.get("n_hits")?,
            query_text: row.get("query_text")?,
        })
    }
}

/// The joined `SELECT` behind [`RetrievalCallListing`] with `tail`
/// appended.
fn listing_sql(tail: &str) -> String {
    format!(
        "SELECT rc.call_id, m.ts, m.tool, rc.corpus_fingerprint, \
                rc.top_k_requested, rc.n_hits, rc.query_text \
         FROM retrieval_calls rc \
         JOIN mcp_tool_calls m ON m.call_id = rc.call_id {tail}"
    )
}

/// One `retrieval_calls` row — the retrieval detail of a logged call.
#[derive(Debug, Clone, PartialEq)]
pub struct RetrievalCall {
    /// The `mcp_tool_calls` row the call was logged under.
    pub call_id: i64,
    /// 16-hex prefix naming the corpus state that served the call.
    pub corpus_fingerprint: String,
    /// How many hits the caller asked for.
    pub top_k_requested: i64,
    /// How many hits actually came back.
    pub n_hits: i64,
    /// The query text, when the caller passed one along.
    pub query_text: Option<String>,
    /// When the row was written, ISO-8601 UTC.
    pub recorded_at: String,
}

impl RetrievalCall {
    /// Build a [`RetrievalCall`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<RetrievalCall> {
        Ok(RetrievalCall {
            call_id: row.get("call_id")?,
            corpus_fingerprint: row.get("corpus_fingerprint")?,
            top_k_requested: row.get("top_k_requested")?,
            n_hits: row.get("n_hits")?,
            query_text: row.get("query_text")?,
            recorded_at: row.get("recorded_at")?,
        })
    }
}

impl Catalog {
    /// Fetch the retrieval detail of one call, or `None` if the call
    /// carries none (a non-retrieval tool, or a row written before the
    /// sidecar existed).
    pub fn retrieval_call(&self, call_id: i64) -> Result<Option<RetrievalCall>> {
        let mut stmt = self.conn.prepare(&select_sql("WHERE call_id = :call_id"))?;
        let row = stmt
            .query_row(
                named_params! { ":call_id": call_id },
                RetrievalCall::from_row,
            )
            .optional()?;
        Ok(row)
    }

    /// List retrieval calls joined with their log rows, newest first.
    /// When `fingerprint` is set, only calls served by that corpus
    /// state are returned; when `last` is set, the result is capped at
    /// that many rows.
    pub fn list_retrieval_calls(
        &self,
        fingerprint: Option<&str>,
        last: Option<usize>,
    ) -> Result<Vec<RetrievalCallListing>> {
        let mut tail = String::new();
        if fingerprint.is_some() {
            tail.push_str("WHERE rc.corpus_fingerprint = :fingerprint ");
        }
        tail.push_str("ORDER BY rc.call_id DESC");
        if let Some(limit) = last {
            tail.push_str(&format!(" LIMIT {limit}"));
        }
        let mut stmt = self.conn.prepare(&listing_sql(&tail))?;
        let rows: Vec<RetrievalCallListing> = if let Some(fingerprint) = fingerprint {
            stmt.query_map(
                named_params! { ":fingerprint": fingerprint },
                RetrievalCallListing::from_row,
            )?
            .collect::<rusqlite::Result<Vec<_>>>()?
        } else {
            stmt.query_map([], RetrievalCallListing::from_row)?
                .collect::<rusqlite::Result<Vec<_>>>()?
        };
        Ok(rows)
    }

    /// Fetch one retrieval call joined with its log row, or `None` if
    /// the call is unknown or carries no retrieval detail.
    pub fn retrieval_call_listing(&self, call_id: i64) -> Result<Option<RetrievalCallListing>> {
        let mut stmt = self
            .conn
            .prepare(&listing_sql("WHERE rc.call_id = :call_id"))?;
        let row = stmt
            .query_row(
                named_params! { ":call_id": call_id },
                RetrievalCallListing::from_row,
            )
            .optional()?;
        Ok(row)
    }

    /// Delete every retrieval call whose fingerprint differs from
    /// `current`, returning the number of deleted calls. Their hits go
    /// with them through the cascading foreign key; the generic
    /// `mcp_tool_calls` log rows stay. Use after a corpus rebuild, when
    /// the recorded hits no longer describe any servable store state.
    pub fn prune_retrieval_calls_with_stale_fingerprint(&self, current: &str) -> Result<usize> {
        let deleted = self.conn.execute(
            "DELETE FROM retrieval_calls WHERE corpus_fingerprint != :current",
            named_params! { ":current": current },
        )?;
        Ok(deleted)
    }

    /// Delete every retrieval call recorded more than `days` days ago,
    /// returning the number of deleted calls. Their hits go with them
    /// through the cascading foreign key; the generic `mcp_tool_calls`
    /// log rows stay.
    pub fn prune_retrieval_calls_older_than(&self, days: u32) -> Result<usize> {
        let deleted = self.conn.execute(
            "DELETE FROM retrieval_calls \
             WHERE recorded_at < datetime('now', :modifier)",
            named_params! { ":modifier": format!("-{days} days") },
        )?;
        Ok(deleted)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::NewMcpToolCall;

    /// Log one parent tool call and its retrieval sidecar with `hits`,
    /// returning the shared `call_id`.
    fn seed_call(catalog: &Catalog, fingerprint: &str, hits: &[(&str, f32)]) -> i64 {
        catalog
            .record_tool_call_with_retrieval(
                &NewMcpToolCall::new("mcp", "search", "ok"),
                Some(&NewRetrievalCall {
                    fingerprint: fingerprint.to_string(),
                    top_k: 10,
                    query_text: Some("what is a monad".to_string()),
                    hits: hits
                        .iter()
                        .map(|(passage_id, distance)| (passage_id.to_string(), *distance))
                        .collect(),
                }),
            )
            .expect("record call with retrieval")
    }

    #[test]
    fn retrieval_call_round_trip_with_three_hits() {
        let catalog = Catalog::open_in_memory().expect("open");
        let hits = [("p-alpha", 0.12), ("p-beta", 0.34), ("p-gamma", 0.56)];
        let call_id = seed_call(&catalog, "deadbeefcafef00d", &hits);

        let call = catalog
            .retrieval_call(call_id)
            .expect("read")
            .expect("present");
        assert_eq!(call.call_id, call_id);
        assert_eq!(call.corpus_fingerprint, "deadbeefcafef00d");
        assert_eq!(call.top_k_requested, 10);
        assert_eq!(call.n_hits, 3);
        assert_eq!(call.query_text.as_deref(), Some("what is a monad"));
        assert!(!call.recorded_at.is_empty());

        let read_hits = catalog.retrieval_hits(call_id).expect("read hits");
        assert_eq!(read_hits.len(), 3);
        for (ord, (passage_id, distance)) in hits.iter().enumerate() {
            assert_eq!(read_hits[ord].ord, ord as i64);
            assert_eq!(read_hits[ord].passage_id, *passage_id);
            assert_eq!(read_hits[ord].distance, f64::from(*distance));
        }
    }

    #[test]
    fn a_call_without_retrieval_detail_reads_none() {
        let catalog = Catalog::open_in_memory().expect("open");
        let call_id = catalog
            .record_tool_call(&NewMcpToolCall::new("cli", "papers_dryrun", "ok"))
            .expect("record parent call");
        assert_eq!(catalog.retrieval_call(call_id).expect("read"), None);
    }

    fn count(catalog: &Catalog, table: &str) -> i64 {
        catalog
            .conn
            .query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |row| {
                row.get(0)
            })
            .expect("count")
    }

    #[test]
    fn list_retrieval_calls_filters_by_fingerprint_and_caps_at_last() {
        let catalog = Catalog::open_in_memory().expect("open");
        let a = seed_call(&catalog, "deadbeefcafef00d", &[("p-alpha", 0.1)]);
        let b = seed_call(&catalog, "0000000000000000", &[("p-beta", 0.2)]);
        let c = seed_call(&catalog, "deadbeefcafef00d", &[("p-gamma", 0.3)]);

        // No filter, no cap: every call, newest first, joined with the
        // log row's tool and timestamp.
        let all = catalog.list_retrieval_calls(None, None).expect("list");
        assert_eq!(
            all.iter().map(|l| l.call_id).collect::<Vec<_>>(),
            vec![c, b, a]
        );
        assert_eq!(all[0].tool, "search");
        assert!(!all[0].ts.is_empty());

        // The fingerprint filter narrows to the matching corpus state.
        let matching = catalog
            .list_retrieval_calls(Some("deadbeefcafef00d"), None)
            .expect("list by fingerprint");
        assert_eq!(
            matching.iter().map(|l| l.call_id).collect::<Vec<_>>(),
            vec![c, a]
        );

        // `last` caps after sorting.
        let one = catalog
            .list_retrieval_calls(None, Some(1))
            .expect("list capped");
        assert_eq!(one.len(), 1);
        assert_eq!(one[0].call_id, c);

        let single = catalog
            .retrieval_call_listing(b)
            .expect("read")
            .expect("present");
        assert_eq!(single.corpus_fingerprint, "0000000000000000");
        assert_eq!(single.n_hits, 1);
    }

    #[test]
    fn prune_with_stale_fingerprint_cascades_to_hits() {
        let catalog = Catalog::open_in_memory().expect("open");
        let stale = seed_call(
            &catalog,
            "0000000000000000",
            &[("p-alpha", 0.1), ("p-beta", 0.2)],
        );
        let current = seed_call(&catalog, "deadbeefcafef00d", &[("p-gamma", 0.3)]);

        let deleted = catalog
            .prune_retrieval_calls_with_stale_fingerprint("deadbeefcafef00d")
            .expect("prune");
        assert_eq!(deleted, 1);
        assert_eq!(catalog.retrieval_call(stale).expect("read stale"), None);
        assert!(
            catalog
                .retrieval_hits(stale)
                .expect("stale hits")
                .is_empty()
        );
        assert!(
            catalog
                .retrieval_call(current)
                .expect("read current")
                .is_some()
        );
        assert_eq!(
            catalog.retrieval_hits(current).expect("current hits").len(),
            1
        );
        // The generic log rows survive the prune untouched.
        assert_eq!(count(&catalog, "mcp_tool_calls"), 2);
    }

    #[test]
    fn prune_older_than_seven_days_keeps_recent() {
        let catalog = Catalog::open_in_memory().expect("open");
        let old = seed_call(&catalog, "deadbeefcafef00d", &[("p-alpha", 0.1)]);
        let recent = seed_call(&catalog, "deadbeefcafef00d", &[("p-beta", 0.2)]);
        catalog
            .conn
            .execute(
                "UPDATE retrieval_calls \
                 SET recorded_at = datetime('now', '-30 days') \
                 WHERE call_id = :call_id",
                named_params! { ":call_id": old },
            )
            .expect("age the old call");

        let deleted = catalog.prune_retrieval_calls_older_than(7).expect("prune");
        assert_eq!(deleted, 1);
        assert_eq!(catalog.retrieval_call(old).expect("read old"), None);
        assert!(catalog.retrieval_hits(old).expect("old hits").is_empty());
        assert!(
            catalog
                .retrieval_call(recent)
                .expect("read recent")
                .is_some()
        );
    }

    #[test]
    fn delete_mcp_tool_call_cascades_to_retrieval_calls_and_hits() {
        let catalog = Catalog::open_in_memory().expect("open");
        catalog
            .conn
            .pragma_update(None, "foreign_keys", "ON")
            .expect("enable foreign keys");
        let call_id = seed_call(&catalog, "deadbeefcafef00d", &[("p-alpha", 0.12)]);

        catalog
            .conn
            .execute(
                "DELETE FROM mcp_tool_calls WHERE call_id = :call_id",
                named_params! { ":call_id": call_id },
            )
            .expect("delete parent");

        let calls: i64 = catalog
            .conn
            .query_row("SELECT COUNT(*) FROM retrieval_calls", [], |row| row.get(0))
            .expect("count calls");
        let hits: i64 = catalog
            .conn
            .query_row("SELECT COUNT(*) FROM retrieval_call_hits", [], |row| {
                row.get(0)
            })
            .expect("count hits");
        assert_eq!((calls, hits), (0, 0));
    }
}
