// SPDX-License-Identifier: Apache-2.0

//! The `works` table — FRBR work identity.
//!
//! A *work* is the abstract creation behind one or more expressions
//! (a translation, an edition). This is a deliberately thin v1 table:
//! by decision D3 the FRBR layer is built but left empty during the
//! pilot, so the module supplies only the minimum to create a work and
//! read it back. Linking an expression to it is a bare soft reference,
//! never a foreign key.

use bookrack_dbkit::{ColumnSpec, TableSpec};
use rusqlite::{OptionalExtension, Row, named_params};

use crate::{Catalog, Result};

/// The single source of truth for the `works` table's schema. Its DDL
/// is rendered from this spec.
pub(crate) const SPEC: TableSpec = TableSpec {
    name: "works",
    comment: Some("FRBR work identity (lightweight; empty in v1 by decision D3)."),
    columns: &[
        ColumnSpec::int("work_id").pk_autoinc(),
        ColumnSpec::text("title"),
        ColumnSpec::text("notes"),
        ColumnSpec::text("curated_at"),
        ColumnSpec::text("curated_by"),
    ],
    composite_pk: None,
    uniques: &[],
    table_checks: &[],
    indexes: &[],
};

/// Insert one work and return its surrogate id. `curated_at` is
/// generated by SQLite so the whole crate shares one timestamp source.
const INSERT_SQL: &str = "INSERT INTO works (title, notes, curated_at, curated_by) \
     VALUES (:title, :notes, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), :curated_by) \
     RETURNING work_id";

/// A `SELECT` of every column with `tail` appended; column list from
/// [`SPEC`].
fn select_sql(tail: &str) -> String {
    format!("SELECT {} FROM works {tail}", SPEC.select_list())
}

/// One `works` row — a curated FRBR work.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Work {
    /// Surrogate key, assigned by the database.
    pub work_id: i64,
    /// The work's title.
    pub title: Option<String>,
    /// Free-form curator notes.
    pub notes: Option<String>,
    /// When the work was curated, ISO-8601 UTC.
    pub curated_at: Option<String>,
    /// Who curated the work.
    pub curated_by: Option<String>,
}

impl Work {
    /// Build a [`Work`] from a row that includes every column.
    fn from_row(row: &Row<'_>) -> rusqlite::Result<Work> {
        Ok(Work {
            work_id: row.get("work_id")?,
            title: row.get("title")?,
            notes: row.get("notes")?,
            curated_at: row.get("curated_at")?,
            curated_by: row.get("curated_by")?,
        })
    }
}

/// A work about to be written. The surrogate `work_id` and the
/// `curated_at` timestamp are assigned by the database. Every other
/// field is optional, so the fields are public; [`NewWork::new`] starts
/// from an empty work.
#[derive(Debug, Clone)]
pub struct NewWork {
    /// The work's title.
    pub title: Option<String>,
    /// Free-form curator notes.
    pub notes: Option<String>,
    /// Who curated the work.
    pub curated_by: Option<String>,
}

impl NewWork {
    /// An empty work, with every field cleared.
    pub fn new() -> NewWork {
        NewWork {
            title: None,
            notes: None,
            curated_by: None,
        }
    }
}

impl Default for NewWork {
    fn default() -> NewWork {
        NewWork::new()
    }
}

impl Catalog {
    /// Insert one work, returning its assigned `work_id`.
    pub fn add_work(&self, new: &NewWork) -> Result<i64> {
        let id = self.conn.query_row(
            INSERT_SQL,
            named_params! {
                ":title": new.title,
                ":notes": new.notes,
                ":curated_by": new.curated_by,
            },
            |row| row.get(0),
        )?;
        Ok(id)
    }

    /// Fetch one work by its id, or `None` if there is no such work.
    pub fn work(&self, work_id: i64) -> Result<Option<Work>> {
        let work = self
            .conn
            .query_row(
                &select_sql("WHERE work_id = :work_id"),
                named_params! { ":work_id": work_id },
                Work::from_row,
            )
            .optional()?;
        Ok(work)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_work_round_trips_every_field() {
        let catalog = Catalog::open_in_memory().expect("open");
        let mut new = NewWork::new();
        new.title = Some("A Work".into());
        new.notes = Some("merged two duplicates".into());
        new.curated_by = Some("human".into());
        let id = catalog.add_work(&new).expect("add");
        assert!(id > 0);

        let read = catalog.work(id).expect("read").expect("present");
        assert_eq!(read.work_id, id);
        assert_eq!(read.title.as_deref(), Some("A Work"));
        assert_eq!(read.notes.as_deref(), Some("merged two duplicates"));
        assert!(read.curated_at.is_some_and(|at| !at.is_empty()));
        assert_eq!(read.curated_by.as_deref(), Some("human"));
    }

    #[test]
    fn a_missing_work_reads_as_none() {
        let catalog = Catalog::open_in_memory().expect("open");
        assert!(catalog.work(404).expect("read").is_none());
    }
}
